### ISSUE TITLE
Please submit questions to this issue tracker instead of mailing list and sourceforge forum.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#1]
The simuPOP repository has been moved from simupop.sourceforge.net to github/BoPeng/simuPOP. The primary website and documentation will stay at sf.net but please submit any question to this issue tracker.

**Comment by Amelia-uoft** [comment]
Hello Bo,

I am new to python and simuPOP. I currently want to try the example code pedigree.py downloaded from http://simupop.sourceforge.net/Cookbook/SimuRareVariants to simulate family data.

However, I got an error if I run "python pedigree.py --gui=batch" as below. 

Traceback (most recent call last):
  File "pedigree.py", line 43, in <module>
    markers = saveMarkerInfoToFile(pop, 'pedigree.map')
  File "/Users/Xiong/Documents/amelia/weixu/sequencing_analysis/data_simulation/simuPOP/pedigree/srv.py", line 568, in saveMarkerInfoToFile
    selCoef = pop.dvars().selCoef
AttributeError: '_dw' object has no attribute 'selCoef'

I previously run srv.py and it was fine. 

Can you help to look at my error and give me some suggestions to solve the problem? Thank you in advance.
