### ISSUE TITLE
Interpretation of recombination rate

### ISSUE THREAD

**Issue by zkamvar** [BoPeng/simuPOP#10]
Hello,

If I use `Recombinator(rates = 0.01)` for a chromosome with 1,000 loci, can it be interpreted that the distance between two adjacent markers is 1 cM and that marker 1 and marker 51 should effectively be unlinked?

**Comment by BoPeng** [comment]
Close but not unlinked because recombination rate between two ends is less than 50x0.01=0.5. There are a few models for such kind of computation.

**Comment by zkamvar** [comment]
> recombination rate between two ends is less than 50x0.01=0.5

I'm not sure I understand. Doesn't a 0.5 recombination rate equate to 50cM?

**Comment by BoPeng** [comment]
Wikipedia has explanation for relationship between cm and probability of
recombination.

**Comment by zkamvar** [comment]
Okay, Thank you. I think I understand now.
