### ISSUE TITLE
simuPOP 1.1.11 doesn't compile with Python 3.11

### ISSUE THREAD

**Issue by skumagai** [BoPeng/simuPOP#102]
Hi,

eval.h is included in
https://github.com/BoPeng/simuPOP/blob/c67ee92308c56e401e3a8406b6cfb849b47d4bfe/src/utility.cpp#L91, but this header file was [removed from cPython 3.11](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-c-api-porting).

Removing the line got me go further, but I hit another issue, which I didn't have time to look at.

**Comment by BoPeng** [comment]
So this head is not needed since it is already included in `Python.h`. Let me have a look.

**Comment by BoPeng** [comment]
Fixed in https://github.com/BoPeng/simuPOP/commit/5bd4bc9cf3e2712cc9f92f05e26153204f39cb03
