### ISSUE TITLE
Changing subpopulation migration parameters 

### ISSUE THREAD

**Issue by cruzan-lab** [BoPeng/simuPOP#104]
I have tried using migr2DSteppingStoneRates to track the spread of mutations across subpopulations. Increasing geneflow results in less spread. I think this is because choosing of migrants is random and not based on fitness so subpopulations with high fitness are swamped by migrants from low-fitness subpopulations. It looks like migrator might be a better solution for this. I need to change migration rates from subpopulations each generation based on fitness so subpopulations with higher fitness contribute more migrants to other subpopulations. Is this possible?

**Comment by BoPeng** [comment]
If you have clear definition of 'high fitness' and 'low fitness', you can define virtual subpopulations and apply different migration rates to them . Basically, you will need to 

1. define vsp based on `fitness` ([doc](http://bopeng.github.io/simuPOP/userGuide_ch4_sec3.html#virtual-subpopulations-and-virtual-splitters))
2. apply a fitness operator, which defines `fitness`, and categorize individuals to their VSPs
3. apply a migrator that migrate from certain VSPs with different rates (see [doc](http://bopeng.github.io/simuPOP/userGuide_ch5_sec4.html#migrate-from-virtual-subpopulations) for details)

If you need more refined control over who can migrate and who cannot, you can define a `PyOperator` that is applied after the fitness operator. In this `PyOperator`, you can set the `migrate_to` field of each individual depending on their `fitness` values.

**Comment by cruzan-lab** [comment]
That makes sense - thanks!

**Comment by cruzan-lab** [comment]
I get an error when I try to query a vsp population size with this code:

import simuPOP as sim
popsize = 10
initfreq = 0.5
pop = sim.Population(size=[popsize, popsize], loci=1, )
sim.InitGenotype(freq=[(1 - initfreq), initfreq])
pop.setVirtualSplitter(sim.GenotypeSplitter(loci=1, alleles=[[0,0],[0,1],[1,1]]))
pop.numVirtualSubPop()
pop.subPopName([0, 1])
sim.dump(pop, structure=False)
pop.subPopSize([0, 'Genotype 1: 0 1'])

It's not clear that individuals are being distributed to VSPs based on their genotype.

**Comment by bioworkflows** [comment]
The problem with your script is that the VSP is defined on locus `1`, which should be `0` (simuPOP uses 0-based index for loci). See [doc](http://bopeng.github.io/simuPOP/userGuide_ch3_sec1.html#zero-based-indexes-absolute-and-relative-indexes) for details.

**Comment by cruzan-lab** [comment]
Thank you for the clarification.
