### ISSUE TITLE
RuntimeError: Cannot set __builtins__ for a dictionary.

### ISSUE THREAD

**Issue by marina-klemm** [BoPeng/simuPOP#108]
Hi there,
I'm relatively new to Python (in comparison to my years-long experience in R) and I'm struggling a bit to start a simple script using simuPOP. I keep running into this "RuntimeError: Cannot set __builtins__ for a dictionary." error even when I follow the simple lines of code from the "FORWARD-TIME SIMULATIONS USING simuPOP" book appendix. 
I'm a Windows user and I use a virtual environment in Spyder with the latest version of Python installed. I migrated to Spyder because VS Code had a number of problems with zlib. However, now I keep facing this new problem and I haven't been able to find any online solution to it. Would you please be able to advise? Thank you so much for your time.

**Comment by BoPeng** [comment]
Could you post the script here?

**Comment by marina-klemm** [comment]
Of course! Thank you!

`# =============================================================================
# Start simuPOP from the basics first, using its appendix
# book chapter
# =============================================================================

import simuPOP as sim

pop = sim.Population(size=1000, loci=2)

pop.evolve(
    initOps=[
        # Initialize individuals with random sex (MALE or FEMALE)
        sim.InitSex(),
        # Initialize individuals with two haplotypes.
        sim.InitGenotype(haplotypes=[[1, 2], [2, 1]])
    ],
    # Random mating using a recombination operator
    matingScheme=sim.RandomMating(ops=sim.Recombinator(rates=0.01)),
    postOps=[
        # Calculate Linkage disequilibrium between the two loci
        sim.Stat(LD=[0, 1], step=10),
        # Print calculated LD values
        sim.PyEval("'%2d: %.2f\n' % (gen, LD[0][1])", step=10),
    ],
    gen=100
)

## It didn't work - "Cannot set __builtins__ for a dictionary"


# =============================================================================
# Creating a population: the most important object of simuPOP
# =============================================================================

pop = sim.Population(size = 1000, ploidy = 42, loci = 10, infoFields = 'fitness')
 ## Creates a population with 1000 individuals,
    # 42 chromosomes with 10 loci each and this information field
    # called 'fitness'.
    # **NOTE: simuPOP uses a name convention that has a plural form if the
    # parameters accept multiple inputs (i.e., infoFields, loci, rates)

pop1 = pop #this just creates a new reference to this pop object.
pop2 = pop.clone() ## This clones pop1; if pop is modified, that will
#alter pop1, but not pop2.

# =============================================================================
#  Access genotype structure of a population  
# =============================================================================
    
pop = sim.Population(size=[20, 30], loci=[10, 20], lociPos=list(range(20, 50)),
                     lociNames=['loc1_%d' % x for x in range(1, 11)] +
                     ['loc2_%d' % x for x in range(1, 21)],
                     alleleNames=['A', 'C', 'G', 'T'], infoFields='a')
pop.ploidy()
pop.numChrom()
pop.numLoci(1) #returns the number of loci on a chromosome    
pop.chromBegin(1)     
pop.infoFields()

pop2.ploidy()    
pop2.numChrom()    
pop2.numLoci(0)    
pop2.infoFields()
    
# =============================================================================
# Subpopulations and virtual subpopulations    
# =============================================================================

pop.popSize() #it added up 20 and 30
pop2.popSize()  
  
pop.numSubPop() #because I provided 20 and 30, it divided it into 2 subpopulations
pop2.numSubPop()    

# VSPs, or virtual subpopulations, can be grouped according to their
# properties, e.g., all males, all age > 20, all genotype (0,0)
# They are defined by splitters

pop3 = sim.Population(size = [200, 400], loci = 5,
                      infoFields= 'x')
sim.initSex(pop3)
## It didn't work - "Cannot set __builtins__ for a dictionary"

sim.initInfo(pop3, lambda: random.randint(0, 3), infoFields='x')`

**Comment by BoPeng** [comment]
I am able to run the scripts without problem after updating

```python
sim.PyEval("'%2d: %.2f\n' % (gen, LD[0][1])", step=10),
```
with
```python
sim.PyEval(r"'%2d: %.2f\n' % (gen, LD[0][1])", step=10),
```

and adding
```python
import random
```

before `random` is used.

**Comment by marina-klemm** [comment]
Amazing! Thank you so much for your time and your help @BoPeng.
