### ISSUE TITLE
Getting simuGWAS example1.py to work

### ISSUE THREAD

**Issue by camdenlopez** [BoPeng/simuPOP#11]
I am trying to get `example1.py` in the `simuGWAS` set of scripts working with Python 3.4.5 (Anaconda 4.2.12) and macOS 10.12.1.

My initial problems were due to Python 3 vs. 2 issues. I fixed those by patching the scripts using 2to3 and by replacing StringType, ListType, etc. with the Python 3 type names in `selectMarkers.py`.

Next, I ran into this error:

```
Traceback (most recent call last):
  File "example1.py", line 102, in <module>
    downloadData([2], logger)
  File "example1.py", line 28, in downloadData
    pop = loadHapMap3.loadHapMapPop(chrom, popName, logger)
  File "/Users/camden/Downloads/simuGWAS/loadHapMap3.py", line 317, in loadHapMapPop
    load_population(pop, diskFiles, allAlleleNames, logger)
  File "/Users/camden/Downloads/simuGWAS/loadHapMap3.py", line 170, in load_population
    pop.individual(ind).setAllele(geno, line_no, ploidy)
TypeError: in method 'Individual_setAllele', argument 4 of type 'int'
```

By email, Dr. Peng suggested checking the type of `ploidy`, and indeed it was a float when it should have been an int (thank you). I was misled by `"argument 4"`. I guess the object itself is argument 1. Converting `ploidy` to int fixed that.

Now I get a segmentation fault:

```
camden$ python example1.py 
simuPOP Version 1.1.7 : Copyright (c) 2004-2016 Bo Peng
Revision 5000 (Jan 21 2016) for Python 3.4.4 (64bit, 0thread)
Random Number Generator is set to mt19937 with random seed 0x3afba4c04f80579.
This is the optimized binary allele version with 2 maximum allelic states.
For more information, please visit http://simupop.sourceforge.net,
or email simupop-list@lists.sourceforge.net (subscription required).
INFO:example1:Loading HapMap3 chromosome 2 of population ASW
INFO:example1:hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.phased.gz is downloaded.
INFO:example1:Genotypes of 20 individuals at 116430 loci are found
INFO:example1:hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.D.phased.gz is downloaded.
INFO:example1:Genotypes of 20 individuals at 116430 loci are found
INFO:example1:hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.unr.phased.gz is downloaded.
INFO:example1:Genotypes of 13 individuals at 116430 loci are found
INFO:example1:Genotypes 53 individuals of 116430 loci (5703 - 242710183 bp) are located
INFO:example1:Importing genotypes of 20 individuals from hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.phased.gz...
INFO:example1:Importing genotypes of 20 individuals from hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.D.phased.gz...
INFO:example1:Importing genotypes of 13 individuals from hapmap3_r2_b36_fwd.consensus.qc.poly.chr2_asw.unr.phased.gz...
Segmentation fault: 11
```

Any idea what might cause this? I tried to find out where exactly the seg fault occurs, but inserting log statements (printing 'line_no' and 'col_no', for example) in the code causes it to take too long to run.

**Comment by BoPeng** [comment]
Could you attached the complete `exampel1.py` to the ticket?

**Comment by camdenlopez** [comment]
Here are the scripts with my modifications:
[scripts_modified.zip](https://github.com/BoPeng/simuPOP/files/604554/scripts_modified.zip)

**Comment by BoPeng** [comment]
This looks again like a python 2/3 problem

```
ind = ind_base + col_no / indCols
```

should be

```
ind = ind_base + col_nu // indCols
```

Also, the segfault is triggered because of the use of "optimized" version of simuPOP, which ignores all runtime check. Please use `optimized=False` in `loadHapMap2.py` and `simuGWAS.py` to use standard module so that there would be proper error message when problems occur.

**Comment by camdenlopez** [comment]
That fixed it, I've successfully run both example1.py and example2.py. Thank you very much for your quick responses! The working scripts are attached.

[scripts_final.zip](https://github.com/BoPeng/simuPOP/files/613798/scripts_final.zip)
