### ISSUE TITLE
Selection with clonal reproduction not working

### ISSUE THREAD

**Issue by cruzan-lab** [BoPeng/simuPOP#112]
I'm trying to simulate clonal evolution with mutation and selection. I set up some extreme values to test the code.
```python
s=1
h=1
Nloci=4
mu=0.001
popsize=10
maxgen=2000

import simuPOP as sim
pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0])
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MapSelector(loci=0, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=1, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=2, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=3, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites = []'), 
        sim.PyExec('meanFit = []')
    ],
    matingScheme=sim.RandomSelection(numOffspring=4, sexMode=None,
        ops = [sim.ParentsTagger(infoFields='fitness'),
        sim.CloneGenoTransmitter(infoFields='fitness')],
        selectionField='fitness'
    ),
    postOps=[
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    gen = maxgen
) 
sim.dump(pop, width=3, max=popsize, structure=False)
```

After 2000 generations sim.dump gives me:

```
SubPopulation 0 (), 10 Individuals:
   0: FU   1  1  1  0 |   1  1  1  0 |  1
   1: FU   1  1  1  0 |   1  1  1  0 |  1
   2: FU   1  1  1  0 |   1  1  1  0 |  1
   3: FU   1  1  1  0 |   1  1  1  0 |  1
   4: FU   1  1  1  0 |   1  1  1  0 |  1
   5: FU   1  1  1  0 |   1  1  1  0 |  1
   6: FU   1  1  1  0 |   1  1  1  0 |  1
   7: FU   1  1  1  0 |   1  1  1  0 |  1
   8: FU   1  1  1  0 |   1  1  1  0 |  1
   9: FU   1  1  1  0 |   1  1  1  0 |  1

>>>
I have also tried MlSelector in preOps:
sim.MlSelector([
     sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
     mode = sim.ADDITIVE)
```

I have also tried selection on the offspring generation. It just seems that MapSelector is not affecting fitness.

Your advice would be greatly appreciated.

**Comment by BoPeng** [comment]
what values of `fit00` did you use? I do not quite understand what you are doing here with `ParentsTagger`, which will pass the index of the mother to the specified `fitness` field. (http://bopeng.github.io/simuPOP/refManual_ch3_sec10.html#class-parentstagger) 

If you want to check mean fitness of the **parents**, you should `Stat` and `Exec` the information in `preOps` after `MapSelector`. Right now you are operating on the offspring generation with wrong `fitness` passed from parents.

**Comment by cruzan-lab** [comment]
fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

I get the same result without ParentsTagger.

I use this statement in preOps:
sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
but I guess you mean I should be using stat instead.
I don't know what you mean by Exec. Do you mean PyExec or InfoExec, and if so, which Python statements should be executed?

**Comment by cruzan-lab** [comment]
Placing this statement in preOps after MapSelector statements generates an error
sim.stat(pop, meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1)

Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "C:\Users\cruzan\Anaconda3\lib\site-packages\simuPOP\__init__.py", line 407, in evolve_pop
    gen = simu.evolve(initOps, preOps, matingScheme, postOps, finalOps, gen)
TypeError: in method 'Simulator_evolve', argument 3 of type 'simuPOP::opList const &'
>>>

**Comment by BoPeng** [comment]
I need first to know what you want to do here. Do you want to get the mean `fitness` of the popularion? If so, why are you useing `meanFit`? Note that you are initializaing `meanFit` at every generation (because it is in `preOps`, not in `initOps`), so the array will only record mean fitness for one generation.

**Comment by BoPeng** [comment]
Note that you are evolving a very small population (10) with a single chromoeome with complete linkage, and with large number of offspring (4), so any "haplotype" can quickly propagate to the entire population.

**Comment by cruzan-lab** [comment]
Yes, I want only high-fitness individuals to divide to produce daughter
cells each generation. Lethal mutations should be eliminated in one
generation. Yes, I should have the number of offspring set to 2.

**Comment by BoPeng** [comment]
I still do not quite understand what you are trying to achieve but the following script runs here. Note that I moved `NSSistes=[]` to `initOps` to properly collect statistics from all generations and print it at the end.

```python
import simuPOP as sim

s=1
h=1
Nloci=4
mu=0.001
popsize=10
maxgen=2000

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MapSelector(loci=0, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=1, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=2, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=3, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.RandomSelection(numOffspring=4, sexMode=None,
        ops = [sim.ParentsTagger(infoFields='fitness'),
        sim.CloneGenoTransmitter(infoFields='fitness')],
        selectionField='fitness'
    ),
    postOps=[


    ],
    gen = maxgen
)
sim.dump(pop, width=3, max=popsize, structure=False)
print(pop.dvars().meanFit)
```

**Comment by cruzan-lab** [comment]
Yes, it runs, but selection (fitness) is having no effect on wether or not a cell divides. With s and h = 1 any cell carrying the mutant allele 1 should die and never reproduce. Instead, we get letha mutations spreading across the population:
>>> sim.dump(pop, width=3, max=popsize, structure=False)
SubPopulation 0 (), 10 Individuals:
   0: FU   0  1  1  0 |   1  1  1  0 |  1
   1: FU   0  1  1  0 |   1  1  1  0 |  1
   2: FU   0  1  1  0 |   1  1  1  0 |  1
   3: FU   0  1  1  0 |   1  1  1  0 |  1
   4: FU   0  1  1  0 |   1  1  1  0 |  1
   5: FU   0  1  1  0 |   1  1  1  0 |  1
   6: FU   0  1  1  0 |   1  1  1  0 |  1
   7: FU   0  1  1  0 |   1  1  1  0 |  1
   8: FU   0  1  1  0 |   1  1  1  0 |  1
   9: FU   0  1  1  0 |   1  1  1  0 |  1

**Comment by BoPeng** [comment]
Your selection is not strong enough and the mutation will segregate along with non-mutated alleles. Also. the haplotype `0110` will be fitter than `0111`.

**Comment by cruzan-lab** [comment]
I guess it is unclearr how to determine fitness of alleles when there is more than one locus (note ploidy=2).
These commands:
        sim.MapSelector(loci=0, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=1, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=2, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
        sim.MapSelector(loci=3, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}),
 look like standard notation where I am identifying the fitness of the genotypes 00, 01, and 11 at EACH locus.

Maybe it would help if you gave an example of how to code so a mutation at any of the four loci would be lethal.

**Comment by BoPeng** [comment]
You are right, I missed this part. You need to use a `sim.MlSelector` to congregate the fitness values. Otherwise, each of these selectors will set `fitness` and the net effect is that only the last one counts.

**Comment by cruzan-lab** [comment]
Yes, I tried that too:
sim.MlSelector([
    sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Nloci)],
    mode = sim.ADDITIVE)
and I got similar results.

But maybe I need to set s=4 to make the mutation to allele 1 lethal at all four loci?

**Comment by BoPeng** [comment]
So you want to completely remove all individuals with any mutation? For an additive model, you only need to make sure 0 fitness value is returned from one of the loci. `s=1` should work.

**Comment by BoPeng** [comment]
The following code works as expected (no mutant allele appears in the offspring population).

```python
import simuPOP as sim

s=1
h=1
Nloci=4
mu=0.001
popsize=10
maxgen=2000

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Nloci)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.RandomSelection(numOffspring=4, sexMode=None,
        ops = [sim.ParentsTagger(infoFields='fitness'),
        sim.CloneGenoTransmitter(infoFields='fitness')],
        selectionField='fitness'
    ),
    postOps=[


    ],
    gen = maxgen
)
sim.dump(pop, width=3, max=popsize, structure=False)
# print(pop.dvars().meanFit)
```

**Comment by cruzan-lab** [comment]
Yes, I just tested the same code.
Thank you.

**Comment by cruzan-lab** [comment]
I'm noticing a problem with this code. I have numberOffspring=1 in the matingScheme. I set genotype frequencies so I have this after one generation (no mutation and no selection):
   0: FU   0  0 |   0  0 |  0
   1: FU   0  0 |   0  0 |  0
   2: FU   0  1 |   0  0 |  0
   3: FU   0  0 |   0  0 |  0
   4: FU   0  0 |   0  0 |  0
   5: FU   0  0 |   0  0 |  0
   6: FU   0  0 |   0  0 |  0
   7: FU   0  0 |   0  0 |  0
   8: FU   0  0 |   0  0 |  0
   9: FU   0  0 |   0  0 |  0
I would expect that each cell would replicate itself each generation so the frequency of the 1 allele in locus 0 would remain the same over generations (assuming that's what numberOffspring=1 means). 
This is what I have after 10 generations:
SubPopulation 0 (), 10 Individuals:
   0: FU   1  0 |   0  0 |  0
   1: FU   0  0 |   0  0 |  0
   2: FU   1  0 |   0  0 |  0
   3: FU   0  0 |   0  0 |  0
   4: FU   0  0 |   0  0 |  0
   5: FU   1  0 |   0  0 |  0
   6: FU   1  0 |   0  0 |  0
   7: FU   1  0 |   0  0 |  0
   8: FU   1  0 |   0  0 |  0
   9: FU   1  0 |   0  0 |  0
The only way this can happen is if not all the individuals are reproducing, which to me does not seem realistic if there is no selection. Is there a way to constrain clonal reproduction so all cells successfully reproduce?

**Comment by BoPeng** [comment]
You are using a random selection mating which choose parents with replacement, so some parents will not reproduce. If you want to make sure all parents can reproduce, use maybe a [SequentialParentChooser](http://bopeng.github.io/simuPOP/refManual_ch2_sec3.html#SequentialParentChooser) (see http://bopeng.github.io/simuPOP/userGuide_ch6_sec3.html for details)

**Comment by cruzan-lab** [comment]
Thanks for this.
I'm trying to implement the SequentialParentChooser:
matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
    sim.OffspringGenerator(ops=[
        sim.CloneGenoTransmitter(infoFields='fitness')],
        numOffspring=1)
),
It returns a difficult to understand error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cruzan\Anaconda3\lib\site-packages\simuPOP\__init__.py", line 407, in evolve_pop
    gen = simu.evolve(initOps, preOps, matingScheme, postOps, finalOps, gen)
ValueError: invalid null reference in method 'Simulator_evolve', argument 5 of type 'simuPOP::opList const &'

**Comment by BoPeng** [comment]
I cannot see what is going on without the complete script. The error message may refer to another parameter.

**Comment by cruzan-lab** [comment]
It's bassically the same script we have been exchanging. I commented-out the mutation and selection statements.

import simuPOP as sim

s=0.1
h=1
Nloci=2
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0
popsize=10
maxgen=10

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness','parent_idx'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(genotypes=[[0,0],[1,1],[0,1],[1,0]], prop=[0.9, 0, 0, 0.1]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        #sim.SNPMutator(u=mu, v=0),
        #sim.MlSelector([
        #    sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
        #    mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.CloneGenoTransmitter(infoFields='fitness')],
            numOffspring=1)
    ),
    postOps=sim.dump(pop, width=3, structure=False),
    gen = maxgen
)
print(pop.dvars().meanFit)

**Comment by BoPeng** [comment]
`postOps` accepts a list.

**Comment by cruzan-lab** [comment]
Got it.
sim.Dumper(pop, width=3, structure=False)
works.

**Comment by cruzan-lab** [comment]
It says in the documentation that Natural selection is not considered in the SequentialParentChooser.
Because of that, I'm trying to apply selection on the offspring, but I'm not seeing any effect as many individuals have low fitness at the end of the simuation. 
This code is more complicated than the previous one:

#Random mutations 1000 loci
import simuPOP as sim

popsize = 20   #germ cell population size
Nloci = 10   #Number of unlinked loci
Pdel = 0.2     #Proportion of deleterious mutations
Ndel = int(Pdel*Nloci)
h = 1
mu = 0.0001                #mutation rate
pd = str(Pdel)
murate = str(mu)
loci = str(Nloci)
maxgen = 200  #Number of cell generations
Niter = 10
outfile = 'CLS_' + 'PropDel=' + pd + '_Loci=' + loci + '_MutRate=' + murate + '_.txt'   #change this to a name for population size 
f = open(outfile, 'w')  #open your output file
f.write("     N    maxgen   mu    Prop_deleterious   Nloci      Nseg_sites  Fitness   Selection \n") 
outfile2 = 'CLS_' + 'PropDel=' + pd + '_Loci=' + loci + '_MutRate=' + murate + 'gens_.txt'

#selection = [0, 2, 4, 6, 8, 10, 20, 30, 40, 50, 70, 100, 200]
selection = [0,1000]

for x in range(0, len(selection)):
    for y in range(Niter):
        pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
        s = (selection[x])/1000
        fit11 = 1-s
        fit10 = 1-(h*s)
        fit00 = 1
                
        pop.evolve(
            initOps=[
                sim.InitSex(maleProp=0),
                sim.InitGenotype(freq=[1, 0]),
            ],
            preOps=[
                sim.SNPMutator(u=mu, v=0),
                sim.MlSelector([
                    sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
                    mode = sim.ADDITIVE),
                sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
                sim.PyExec('NSSites = []'), 
                sim.PyExec('meanFit = []')
            ],
            matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
                sim.OffspringGenerator(ops=[
                    sim.MlSelector([
                        sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
                        mode = sim.ADDITIVE),
                    sim.CloneGenoTransmitter(infoFields='fitness')],
                    numOffspring=1)
            ),
            postOps=[
                sim.stat(pop, meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
                sim.PyExec('NSSites.append(numOfSegSites)'),
                sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
                sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
                    step=1),
                sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
                    step=10, output='>>outfile_gen.txt')
            ],
            gen = maxgen
        )  
        Nsites = (pop.dvars().NSSites) #extract list of seg sites
        Mfit = (pop.dvars().meanFit)
        f = open(outfile, 'a')
        f.write(" %10d %6d %12.6f %10.4f %6d %6d %16.4f %10.4f \n" % (popsize, maxgen, mu, Pdel, Nloci, Nsites[0], Mfit[0], s)) 
        f.close()
        sim.dump(pop, width=3, max=popsize, structure=False)

**Comment by BoPeng** [comment]
First, please use tripe ticks (` ```python `) to quote your code, which allows easier reading of your posts.

during mating selection is a different beast. Whereas `fitness` of parents are compares against other parents and are relative, `fitness` of offspring are 'probability of survival' and is absolute. Without looking at your code a fitness of 0.9 is pretty weak since 90% of offspring will survive and may not be as strong as you have hoped. To check the effect of selection, you can print the fitness of the parental selection (assign `fitness`, calculate mean fitness, although `fitness` will not be used), then the fitness of the surviving offspring.

**Comment by cruzan-lab** [comment]
I'm still getting low-fitness cell lineages surviging with this simpler code.
'''python
import simuPOP as sim

s=0.1
h=0.5
Nloci=10
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0.001
popsize=10
maxgen=1000

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.CloneGenoTransmitter(infoFields='fitness')],
            numOffspring=1)
    ),
    postOps=sim.Dumper(pop, width=3, structure=False),
    gen = maxgen
)
print(pop.dvars().meanFit)

**Comment by cruzan-lab** [comment]
I'm still tryng to figure out what you mean by tripe ticks.

**Comment by BoPeng** [comment]
Triple backticks is described at https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by BoPeng** [comment]
For your code `SequentialParentChooser` does not honor `fitness` so no nature selection was performed. My suggestion of putting `MlSelector` in `preOps` is to calculate the (average) population fitness of the parental generation. After you apply during mating selection using `MlSelector` as an operator in the mating scheme, you can do the same thing in `postOps` to calculate the population fitness of the offspring generation, in this way you can see if natural selection during mating has helped improve average fitness.

**Comment by cruzan-lab** [comment]
I'm not sure how to use MlSelector as an operator in the mating scheme. Using the code below it appears that cells with lower fitness are successfully reproducing when they should be replaced by a progeny from a high fitness cell lineage with numOffspring=1. If I increase this to 2 then low-fitness cell lines start replacing the high fitness ones. 

```
import simuPOP as sim

s=0.1
h=0.5
Nloci=10
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0.01
popsize=10
maxgen=10

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.CloneGenoTransmitter(infoFields='fitness')],
            numOffspring=2)
    ),
    postOps=[
        sim.Dumper(pop, width=3, structure=False),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
    ],
    gen = maxgen
)
print(pop.dvars().meanFit)
```

**Comment by BoPeng** [comment]
I think http://bopeng.github.io/simuPOP/userGuide_ch5_sec9.html#natural-selection-through-the-selection-of-offspring is pretty clear on how to perform natural selection based on absolute fitness. You `MlSelector` in `preOps` and `postOps` will not work because your mating scheme does not select either parents (require a `RandomParentSelector`) or offspring (require a selector like `MlSelector`).

**Comment by cruzan-lab** [comment]
Yes, I had actually tried what you suggested but I'm still seeing low-fitness cell lines increasing in frequency even when selection is pretty strong. The code is below:
```
import simuPOP as sim

s=0.2
h=0.5
Nloci=10
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0.001
popsize=10
maxgen=500

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.MlSelector([
                sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
                mode = sim.ADDITIVE),
            sim.CloneGenoTransmitter(
            infoFields='fitness')],
            numOffspring=2)
    ),
    postOps=[
        sim.Dumper(pop, width=3, structure=False),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
    ],
    gen = maxgen
)
print(pop.dvars().meanFit)
```

**Comment by BoPeng** [comment]
Can you try to change the order of `CloneGenoTransmitter` and `MlSelector`. The problem here is that you are applying `MlSelector` to individuals with random genotype (or all zero genotype, nevertheless undefined) so you need to transmit genotype before applying selector.

**Comment by cruzan-lab** [comment]
Like this? That's not working either.

```
import simuPOP as sim

s=0.4
h=1
Nloci=10
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0.001
popsize=10
maxgen=500

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.CloneGenoTransmitter(
                infoFields='fitness'),
            sim.MlSelector([
                sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
                mode = sim.ADDITIVE),
            ],
            numOffspring=2)
    ),
    postOps=[
        sim.Dumper(pop, width=3, structure=False),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
    ],
    gen = maxgen
)
print(pop.dvars().meanFit)
```

**Comment by BoPeng** [comment]
Yes, selection should work in this case. Could you elaborate what you meant by "not working"?

**Comment by cruzan-lab** [comment]
Low-fitness cell lineages are still increasing in abundance.

**Comment by BoPeng** [comment]
If you put 

```
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyEval(r"'Gen: %2d off #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
```
to `postOps` and compare the average fitness of offspring generation, it is almost always higher than parental generation, so selection works. If you increase `s`, the selection will become stronger and almost eliminate any mutation.

Why low-fitness cell lineage increases under your parameter setting is an interesting question.

**Comment by BoPeng** [comment]
> Why low-fitness cell lineage increases under your parameter setting is an interesting question.

Let us say you have a mutation, and with `numOffspring=2` you get two offspring, and with `s=0.4`, maybe less than 1 offspring will be removed, so in the end the mutation will very likely survive to the next generation.

**Comment by cruzan-lab** [comment]
After more testing it looks like this version of the program is working. I reduced numOffspring to 1 and put the MlSelector prior to the CloneGenoTransmitter in the matingScheme. I reduced s to 0.1 with h = 1. Deleterious mutations will persist for a couple of generations but are eventually removed. 
```
import simuPOP as sim

s=0.1
h=1
Nloci=10
Pdel = 0.2
Ndel = int(Pdel*Nloci)
mu=0.005
popsize=10
maxgen=20

fit11 = 1-s
fit10 = 1-(h*s)
fit00 = 1

pop = sim.Population(size=popsize, loci=[Nloci], ploidy=2, infoFields=['fitness'])
pop.evolve(
    initOps=[
        sim.InitSex(maleProp=0),
        sim.InitGenotype(freq=[1, 0]),
        sim.PyExec('NSSites = []'),
        sim.PyExec('meanFit = []')
    ],
    preOps=[
        sim.SNPMutator(u=mu, v=0),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
        sim.Stat(meanOfInfo='fitness', numOfSegSites=sim.ALL_AVAIL, step=1),
        sim.PyExec('NSSites.append(numOfSegSites)'),
        sim.PyExec('meanFit.append(meanOfInfo["fitness"])'),
        sim.PyEval(r"'Gen: %2d #seg sites: %d mean fitness: %8.3f \n' % (gen, numOfSegSites, meanOfInfo['fitness'])",
            step=1),
    ],
    matingScheme=sim.HomoMating(sim.SequentialParentChooser(),
        sim.OffspringGenerator(ops=[
            sim.MlSelector([
                sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
                mode = sim.ADDITIVE),
            sim.CloneGenoTransmitter(
                infoFields='fitness'),
            ],
            numOffspring=1)
    ),
    postOps=[
        sim.Dumper(pop, width=3, structure=False),
        sim.MlSelector([
            sim.MapSelector(loci=y, fitness={(0,0):fit00, (0,1):fit10, (1,1):fit11}) for y in range(Ndel)],
            mode = sim.ADDITIVE),
    ],
    gen = maxgen
)
print(pop.dvars().meanFit)
```

**Comment by BoPeng** [comment]
Why do you put `sim.MlSelector` before `sim.CloneGenoTransmitter`? The genotype of offspring is technically undefined at that point.

**Comment by cruzan-lab** [comment]
OK, I switched it back. It'a working as long as the mutation rate is not too high relative to selection.
