### ISSUE TITLE
Cannot use frequency list to initialize beginFreq in trajectory

### ISSUE THREAD

**Issue by marina-klemm** [BoPeng/simuPOP#113]
Kia ora Bo Peng,
I keep running into the same error when trying to run my simulation using my mtDNA frequencies file inside the beginFreq at my trajectory function. I have the frequency for 100 alleles and I'm running the simulation with 100 loci. However, whenever I try to define the trajectory, it says "Initial frequency should be provided for each locus (nLoci) or each locus at each subpopulation (nLoci * len(N))."
Is there a way around it? My code follows attached in txt.

Additionally, is there a limit of generations or individuals that can be input into a trajectory? 
I verified that I cannot have a simulation with less than 80 generations, since that gives me the error "AttributeError: 'NoneType' object has no attribute 'func'".
In my simulation, I start with 30,000 individuals and my population goes through a bottleneck of 40 within 10 generations. I found trajectory does not run with such a large number of individuals and perhaps with a narrow bottleneck like this. 
[traj.func_error.txt](https://github.com/BoPeng/simuPOP/files/13454059/traj.func_error.txt)

Thank you so very much for your time.
Ngā mihi,
Marina.

**Comment by BoPeng** [comment]
I get `mtDNA_1.txt not found` error when I tried to reproduce your problem.

**Comment by BoPeng** [comment]
I notice that your `formatted_list` is a list of strings like

```
['0.130066116932049, 0', '0.0365202462650868, 0', '0.0457264089847202, 0', '0.0843284207640962, 0',
```

where the documentation says

```
        beginFreq
            The initial allele frequency of involved loci in all subpopulations.
            It can be a number (same frequency for all loci in all
            subpopulations), or a list of frequencies for each locus (same
            frequency in all subpopulations), or a list of frequencies for each
            locus in each subpopulation in the order of ``loc0_sp0``,
            ``loc1_sp0``, ..., ``loc0_sp1``, ``loc1_sp1``, ... and so on.
```
