### ISSUE TITLE
Documentation of weights in HeteroMating?

### ISSUE THREAD

**Issue by petrelharp** [BoPeng/simuPOP#12]
To me at least, the documentation of what exactly the 'weights' do in [HeteroMating](http://simupop.sourceforge.net/manual_svn/build/refManual_ch2_sec3.html#class-heteromating) is not sufficiently precise.  Can you explain?  How exactly is it determined how many offspring are produced  from which type of mating?

For instance, under
```
HeteroMating( [ 
    Mating1(...,weight=-2), 
    Mating2(...,weight=-1), 
    Mating3(...,weight=0), 
    Mating4(...,weight=1), 
    Mating5(...,weight=2) ], ... )
```
with a target population of size N, how is it determined how many are produced through each mating scheme?

**Comment by BoPeng** [comment]
Did you come across the example in [this chapter of simuPOP documentation](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch6_sec1.html#heterogeneous-mating-schemes)?

**Comment by petrelharp** [comment]
No, but I should have!

That is crystal-clear, except that I want to check on one point of clarification: suppose weights are (1,2,3) and N=100.  From the documentation, it looks like the number of offspring from each should be 100/6, 200/6, and 300/6... exactly, not that each offspring chooses a mating scheme independently from those weights?  But, these are not integers?

**Comment by ashander** [comment]
The same (non-integer) issue is raised with fractional negative weights.

**Comment by BoPeng** [comment]
simuPOP first determines the number of offspring for each mating scheme, and uses corresponding mating schemes to produce the offspring. The offspring are by default randomized so it appears that offspring are produced by "random" mating scheme.

The non-integer cases are not handled in an extremely clever way. Basically all negative weights are handled, then positive weights, and the last subpopulation is adjusted to accommodate the numerical differences caused by non-integers. This could be problematic if you have a large number of very small subpopulations ....

**Comment by petrelharp** [comment]
So, just to be extra certain, in the above situation the numbers are `16 = 100/6`, `33 = 200/6`, and `51 = 100 - 16 - 33`?  And, not Multinomially distributed with those means?

**Comment by BoPeng** [comment]
Yes, your calculation is correct. The weights are designed to be proportions, not probabilities, so no random distributions is used here. A **proper** solution for non-integer case, however, would be rounding for each mating scheme, and use a random distribution for the remaining individuals. If this is important for your simulation, you can file a feature request or send a pull-request if you are able to implement it by yourself (the relevant code at line 1725 of [mating.cpp](https://github.com/BoPeng/simuPOP/blob/master/src/mating.cpp) ).

**Comment by ashander** [comment]
Side comment: you can link directly to a line by appending `#<line number>` to a github url, so
