### ISSUE TITLE
Cookbook links from simuPOP homepage, User Guide and Reference Manual are broken

### ISSUE THREAD

**Issue by lfmcmillan** [BoPeng/simuPOP#120]
The homepage (https://bopeng.github.io/simuPOP/) has a broken link in the left-hand menu to the cookbook: https://github.com/BoPeng/simuPOP/cookbook

The Reference Manual has the same broken link in the left-hand menu to the cookbook

The "What is simuPOP?" page of the User Guide (http://bopeng.github.io/simuPOP/userGuide_ch2_sec1.html) also provides the same broken link

The readthedocs version of the User Guide provides a broken link to a sourceforge version of the cookbook: http://simupop.sourceforge.net/cookbook (see near the bottom of https://simupop.readthedocs.io/en/latest/userGuide_ch2_sec1.html)

If you search for "simuPOP cookbook" on google, none of the first 10 links are direct links to the cookbook. One or two of them are links to the Bioinformatics with Python Cookbook, but only the first and second editions of that book even mention simuPOP, and the third edition cut out all the simuPOP bits.

If the cookbook has been relocated then please fix the links, thanks very much.

**Comment by BoPeng** [comment]
Yes, cookbook should refer to https://github.com/BoPeng/simuPOP-examples, especially its example directory, and the sourceforge links should have been gone long ago. The figure should point to https://github.com/BoPeng/simuPOP/blob/master/doc/figures/evolve.png 

Do you have time to work on a PR?

**Comment by lfmcmillan** [comment]
Yes, I think so. Do you want it to still be referred to as the Cookbook, or
the Examples (i.e. links changed or also change text references)?

**Comment by BoPeng** [comment]
Thanks! Just examples would do since they are not organized as a book (with topics and sections).

**Comment by lfmcmillan** [comment]
OK, I think I'm fixing the source files since I don't know how to rebuild
the HTML files from the source.
