### ISSUE TITLE
Exporter only writes a single file, even with `gen` in `output=` string

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#13]
The [documentation for Exporter](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch7_sec2.html#export-simupop-population-to-files-in-structure-genepop-fstat-phylip-ped-map-ms-and-csv-formats-function-export-and-operator-exporter) suggests one could provide a `simuPOP.utils.Exporter` to `postOps` and have export done at each generation of evolution:

>An operator Exporter is also provided so that you could export populations during evolution. Operator arameters such as output, begin, end, step, at, reps, and subPops are supported so that you could export subsets of individuals at multiple generations using different file names (e.g. output='!''%d.ped'' % gen' to output to different files at different generations).

With simuPOP 1.1.7 and python 3.5.2, the code below only produces output to one file, even with multiple generations, and it appears the output is only from the final generation. Am I misunderstanding the documentation or misspecifying the `output` string?

```python
import simuPOP as sim
import simuPOP.utils as u
p = sim.Population(20)
p.evolve(
    gen=5,
    initOps=[sim.InitSex()], 
    preOps=[u.Exporter(format='CSV', output='!"try_output%d.csv" % gen'), ],
    matingScheme=sim.RandomMating(subPopSize=5)
)
```

```sh
$ ls  && wc -l try_output0.csv
try_output0.csv
6 try_output0.csv
```

**Comment by ashander** [comment]
A related question: Is it possible in an `Exporter` to write generation directly (e.g. along with the InfoFields?

**Comment by BoPeng** [comment]
Thank you for reporting the bug, which has been fixed. If you do not want to compile from source or wait for the next release of simuPOP, please use

```
sim.PyOperator(func=lambda pop: u.export(pop, format='CSV', output='!"try_output%d.csv" % gen') is None)
```
in place of

```
Exporter(format='CSV', output='!"try_output%d.csv" % gen')
```
for now.

**Comment by BoPeng** [comment]
The answer to you second question depends on how you would like to output generation number. The generation number is a "global" variable in that sense that it is the same for all individuals, so it is wasteful to output for each individual. Without checking the details of each format, I do not think any of the supported format accepts such meta information.

If you just want to output generation number in your csv files, perhaps you can do something like:

```
PyEval(r'"Generation=%d\n" % gen', output='>>output.txt')
Exporter(format='csv', output='>>output.txt'),
```
which puts all `csv` output in a single file, with generation number in between.

**Comment by ashander** [comment]
Thanks! Happy to help find a bug. And the `lambda` version works great for now.

I'll close this issue, but I am curious if there's a quick answer to my follow-up (which would make my end goal easier): Is there a way to write generation directly (e.g. along with the InfoFields) in an `Exporter` (or `export` expression)?

Thanks again,
