### ISSUE TITLE
Elegant way to deal with low/zero populations size in dynamically-growing populations?

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#15]
In a spatially-extensive population that is growing naturally (individuals try to find mates and reproduce), occasionally individuals will fail to find mates. In simuPOP, we need to deal with this at the time of setting the `subPopSize` in a mating scheme. 

One way to do this: each female in a subpopulation tries to produce offspring; at the end of a generation if there weren't any males in the population these offspring are not actually produced. Some code for this approach is given below.

My question: Is there a more elegant way, in a model where the next generation size depends on the number of females, to deal with the situation of there being no males in a subpopuation?

```py
import simuPOP as sim
numoff = 2  # Global used in in demoModel and evolve

def demoModel(pop):
    size = []
    for n in range(pop.numSubPop()):
        print("running subpop {}".format(n))
        this_pop = []
        male_in_pop = False
        for ind in pop.individuals(subPop=n):
            if ind.sex() == sim.FEMALE:
                this_pop.append(numoff)
                print("  made {} offspring".format(numoff))
            elif ind.sex() == sim.MALE:
                male_in_pop = True
        if not male_in_pop:
            this_pop = []
        print("  generation: {}".format(this_pop))
        size.append(sum(this_pop))
    return size

sim.setOptions(seed=112)
initial_size = [2, 1]
p = sim.Population(initial_size,
                   infoFields=['migrate_to'])
sim.initSex(p, sex=[sim.MALE, sim.FEMALE, sim.FEMALE])

sim.dump(p, structure = False)
p.evolve(
    matingScheme=sim.HomoMating(
        chooser = sim.CombinedParentsChooser(
            sim.RandomParentChooser(replacement=True, sexChoice=sim.MALE_ONLY),
            sim.SequentialParentChooser(sexChoice=sim.FEMALE_ONLY),
        ),
        generator = sim.OffspringGenerator( ops = [
            sim.MendelianGenoTransmitter(),
        ],
            numOffspring=numoff),
        subPopSize=demoModel,
    ),
    gen=1,
)
```

The `demoModel` code was adapted from [this thread on the old mailing list](https://sourceforge.net/p/simupop/mailman/message/33232362/)

**Comment by BoPeng** [comment]
Are you trying to find an elegant way to *detect* the problem or *fix* the problem (somehow)? If you simply need to find subpopulations without male, or create a subpopulation will sizes proportional to number of females, you can use a `stat` operator as follows:

```
def demoModel(pop):
    stat(pop, numOfMales=True, vars=['numOfMales_sp', 'numOfFemales_sp'])
    m_f = [(pop.dvars(i).numOfMales, pop.dvars(i).numOfFemales) for i in range(pop.numSubPop())]
    return [f*1.1 if m > 0 else 0 for m,f in m_f]
```

Here we use the special per-subpopulation variable name `numOfMales_sp` to get number of males in each subpopulation.

**Comment by ashander** [comment]
Thanks for the better way to detect the problem using `numOfMales_sp`. Something like this will work for me.

To clarify, though, I really had both questions: 
- for the first, _detect_ question, I was curious about how to more elegantly detect the problem. For this, your solution will work well,
- for the second, _fix_ question, "elegant" is definitely the wrong word. But I was curious if there was a built-in way to automatically set populations where such failures occur to 0.

**Comment by BoPeng** [comment]
I agree with you that *set-to-zero* is the most natural way to _fix_ the problem, but there has been cases where certain (plant? animal?) population turns to complete self-fertilization when cross-fertilization becomes infeasible, and some people even change the sex of a few parents just to make the simulations continue. Because some operators expect offspring population having size set by `subPopSize`, producing a population with less-than-expected size might cause problem....

So in the end no _solution_ was implemented and the choice is left to the user.

**Comment by petrelharp** [comment]
Makes sense. I think the solution is: set the population size based on *both* the number of females and the number of males.  This is what any automatic "set to zero" solution would be doing, effectively, anyhow.

**Comment by ashander** [comment]
@BoPeng it makes sense that you didn't bake in a solution, as simupop provides so much flexibility in mating systems

@petrelharp +1 and using `stat` and `pop.dvars()` as suggested will work well for this. 

Thanks!
