### ISSUE TITLE
example of how to implement user-specified recombination breakpoints

### ISSUE THREAD

**Issue by petrelharp** [BoPeng/simuPOP#18]
I'm trying to take control of recombination explicitly (so that I can record things about it - [work in progress](https://github.com/ashander/ftprime)).  I have a large number of selected loci, with positions along the chromosome, and would like to (a) pick crossovers uniformly along the chromosome, and then (b) transmit genotypes based on where the crossovers lie relative to the positions of the loci.  I'm aware of the `output` functionality, but we really want to specify these things ourselves.

it looks like I need to extend GenoTransmitter - but, I'm not finding any examples, or an interface, to do this.  It seems like I'd just need additional parameters in `copyChromosome()` - say, `startLocus` and `endLocus` to give the indices of the first and last loci to be copied.  Does this functionality exist?

**Comment by ashander** [comment]
What about [Recombinator](http://simupop.sourceforge.net/manual_svn/build/refManual_ch3_sec5.html#Recombinator) ?

There's an example in the user guide of [tracking all recombination events](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch5_sec5.html#tracking-all-recombination-events) 
(into a log file, in that case but perhaps still a good starting point?).

**Comment by petrelharp** [comment]
Good point - that's what I'm using now; it would also suffice to extend Recombinator to do something with the breakpoints in python, rather than going out though a file.

**Comment by BoPeng** [comment]
simuPOP operators can output to functions so you do not have to parse any file. For example [srv.py](http://simupop.sourceforge.net/Cookbook/SimuRareVariants) has something like:

```
class fitnessCollector:
    def __init__(self):
        self.selCoef = {}
    def getCoef(self, lines):
        for line in lines.strip().split('\n'):
            mut, sel, h = line.split()
            self.selCoef[int(mut)] = float(sel), float(h)
```

and an object of this class is passed to an operator

```
MutSpaceSelector(selDist=selDist, mode=mode, output=collector.getCoef)
```
The object then parses output of the operator and collect information it needs.

**Comment by petrelharp** [comment]
Ah ha - that should work.

Thanks!
