### ISSUE TITLE
Can one avoid an invalid iterator ValueError with migration and empty populations?

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#19]
Is there a way to gracefully exit instead of causing an error when a population becomes empty and a migration operator is being used?  In the example below, a migration operator is attempted on an empty population and it raises a `ValueError`

```python
import simuPOP as sim
from simuPOP.demography import migr2DSteppingStoneRates
pop = sim.Population([0] * 2, infoFields='migrate_to')
pop.evolve(gen=1, 
                   preOps=sim.Migrator(rate=[[.1, .9], [.9, .1]], 
                   mode=sim.BY_PROBABILITY))
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-d5a289a41992> in <module>()
      4 pop.evolve(gen=1, 
      5                    preOps=sim.Migrator(rate=[[.1, .9], [.9, .1]], 
----> 6                    mode=sim.BY_PROBABILITY))

/home/jaime/miniconda3/envs/tortoise-conda/lib/python3.5/site-packages/simuPOP/__init__.py in evolve_pop(self, initOps, preOps, matingScheme, postOps, finalOps, gen, dryrun)
    405     simu = Simulator(self)
    406     # evolve
--> 407     gen = simu.evolve(initOps, preOps, matingScheme, postOps, finalOps, gen)
    408     # get the evolved population
    409     self.swap(simu.population(0))

ValueError: individual.h: 874 Can not refer to an invalid iterator

```

**Comment by BoPeng** [comment]
In this case, migration should be allowed (but does not move anyone), right?

**Comment by ashander** [comment]
Yeah, I think that's the most flexible behavior.

One might want the simulation to continue, even with an empty population. For example, if there were some event-based migrations into the population in the future

**Comment by BoPeng** [comment]
I am checking the source of the problem. Most likely some logic like "if pop size is 0" should be added.

**Comment by BoPeng** [comment]
This should have been fixed, although you will have to compile simuPOP from source. You could use something like:

```
lambda pop: True if pop.popSize() ==0 else (sim.migrate(pop, rate=...) is None)
```

in place of your `Migrator` to get around of the problem at the Python level.

**Comment by ashander** [comment]
Great. I haven't recompiled but the patch works for now. I'll let you know if there's any issue once I recompile
