### ISSUE TITLE
Using simuPOP and scipy Simultaneously

### ISSUE THREAD

**Issue by veritas2all** [BoPeng/simuPOP#2]
Hello,

I am having difficulty using simuPOP and scipy simultaneously. I am running Python 3 through PyCharm. When I attempt to set the interpreter and select the Python version installed with Anaconda, I am unable to add the simuPOP package. Based on the instructions for installing the simuPOP package on https://anaconda.org/bpeng/simuPOP I used Windows PowerShell to run the conda install command "conda install -c bpeng simupop=1.1.7". simuPOP was not installed. Below is the feedback I received? How can I get simuPOP to run alongside other packages such as scipy? Is there another IDE that I should consider?

PS C:\Users\Veritas> conda install -c bpeng simupop=1.1.7
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 3.5*
  - simupop 1.1.7*
Use "conda info <package>" to see the dependencies for each package.

The following specifications were found to be in conflict:
  - python 3.5*
  - simupop 1.1.7*
Use "conda info <package>" to see the dependencies for each package.

**Comment by BoPeng** [comment]
Could you let me know the exact environment you are using? Namely version of Python, OS etc?
