### ISSUE TITLE
Problem with pedigree.py for srv simulator

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#24]
Hello Bo,

I am new to python and simuPOP. I currently want to try the example code pedigree.py downloaded from http://simupop.sourceforge.net/Cookbook/SimuRareVariants to simulate family data.

However, I got an error if I run "python pedigree.py --gui=batch" as below.

```
Traceback (most recent call last):
File "pedigree.py", line 43, in 
markers = saveMarkerInfoToFile(pop, 'pedigree.map')
File "/Users/Xiong/Documents/amelia/weixu/sequencing_analysis/data_simulation/simuPOP/pedigree/srv.py", line 568, in saveMarkerInfoToFile
selCoef = pop.dvars().selCoef
AttributeError: '_dw' object has no attribute 'selCoef'
```
I previously run srv.py and it was fine.

Can you help to look at my error and give me some suggestions to solve the problem? Thank you in advance.

**Comment by BoPeng** [comment]
The scripts were written in Python 2.7 and need to be updated to Python 3 to be run here.... I have not been able to update all but the problem you were seeing is caused by an update of `srv.py` (after `pedigree.py`) that saves population before `selCoef` is saved to the population. You should be able to get around of this problem by using the population returned by `simuRareVariants` and not the one loaded from `example.pop`, more specifically, change lines 17 to 23 of `pedigree.py` to

```
#
# We only need pop file to further analysis. No .ped file is saved.
pop = simuRareVariants(regions=['chr1:1..63000'], N=(8100, 8100, 7900, 900000),
    G=(20000, 10, 370), mu=1.8e-8, steps=[100,1,10],
    selModel='multiplicative', selDist='constant', selCoef=None,
    popFile='example.pop')
# load population
# print('Loading population example.pop')
# pop = sim.loadPopulation('example.pop')
```

Let me know if this fixes the problem and if you encounter more problems later on.

**Comment by Amelia-uoft** [comment]
Thank you so much Bo. It works for me!

Amelia

**Comment by BoPeng** [comment]
I have moved all simuPOP examples to repository [simuPOP-examples](https://github.com/BoPeng/simuPOP-examples) so that they can actually be fixed if they are broken.

**Comment by Amelia-uoft** [comment]
Hi Bo,

I had a new problem running the pedigree code. It occurs at the following line:

sample = sampling.drawThreeGenFamilySample(pop, families=100, numOffspring=2, pedSize=4, numOfAffected=1)

Warning: number of requested Pedigrees 100 is greater than what exists (0).
Warning: not enough non-overlapping Pedigrees are found (requested 100, found 0).
Writing mutants of 0 individuals to pedigree.mutMutants are saved to file pedigree.mut

I also tried to change the parameters in the function above. However, none of them worked. I think it should not because of the parameters that I chose. Could you please have a look at my problem?

Thank you!

**Comment by BoPeng** [comment]
I am in the precess of releasing the next version of simuPOP and updating srv and other scripts. This version of simuPOP will only support python 3 though, is it possible for you to upgrade to Python 3 so that we can be on the same pace?

**Comment by Amelia-uoft** [comment]
Hi Bo,

I am currently using python 3.4, and the newer version of srv.py and pedigree.py from github. But there is still problem to run it. The error message is:

Traceback (most recent call last):
  File "pedigree_new.py", line 9, in <module>
    from srv import simuRareVariants, saveMarkerInfoToFile, saveMutantsToFile
  File "/Users/Xiong/Documents/amelia/weixu/sequencing_analysis/data_simulation/simuPOP/pedigree/srv.py", line 363
    for idx,loc in enumerate(apop.lociPos()):
    ^
IndentationError: unexpected indent

I am wondering whether it means python and .py file still do not match. If it is, what I can do?

Thank you for your kind help!

**Comment by BoPeng** [comment]
Thanks. I just moved srv to [simuPOP-examples](https://github.com/BoPeng/simuPOP-examples/tree/master/published/simuRareVariants) and have not been able to work on it. I was just suggesting that you use Python 3.x and check out srv from the new location. I will get back to you soon.

**Comment by BoPeng** [comment]
Moved to https://github.com/BoPeng/simuPOP-examples/issues/1
