### ISSUE TITLE
simuPOP doc conversion process

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#27]
simuPOP's documentation is currently maintained in a very complex way. Schematically, 

![doc_generation](https://cloud.githubusercontent.com/assets/9889312/22628036/44d12dce-eb92-11e6-936c-9c211a06ff98.png)

I have converted `doxy2swig.py` from 2 to 3, but the `tex` to `rst` converter was from a very old branch of `docutils` and I had to patch it to work with simuPOP. It would be a lot of work to convert that piece of code. Also, it is currently a bit complicated to update user guide even with the help of a make file.

Not sure if I should abandon all PDF format output, and use only markdown for online documentation.

**Comment by BoPeng** [comment]
Perhaps a better way to document simuPOP is to use Jupyter notebook in which all examples can be executed. I would have to convert the existing documentation to markdown files and then insert them to new documents, which seems to be a lot of work.

It is also unclear how to generate Jupyter notebooks for references. However, because the reference manual is just a collection of individual references, we could avoid the `tex -> rst` conversion for the generation of reference manual.

**Comment by ashander** [comment]
It does seem like a lot of work to convert the sources. If the main current need is to convert `tex` to `rst` (assuming `rst` must be used until a larger rewrite of the docs system), could [pandoc](http://pandoc.org/demos.html) help? It seems capable (in theory) of doing `tex -> rst` conversion

**Comment by BoPeng** [comment]
Yes, the document processing system was developed 10+ years ago, perhaps before pandoc was available. Since the weak link at this point is the `tex` to `rst` converter, I should perhaps try pandoc.

**Comment by ashander** [comment]
Pandoc could also help start the (longer term) migration of sources to markdown, if that's determined to be a good course of action. 

For example (modifying [suggestion here](https://www.lemmster.de/lyx-export-to-markdown.html) to work with current pandoc syntax):

```sh
lyx --export latex file.lyx
pandoc --wrap=none markdown file.tex -o file.md
```

**Comment by madsenibis** [comment]
Is there an update on how documentation will be updated?  I am a long-time user of simuPOP, coming back to do more work after a couple of years on other projects, and the book is TRAGICALLY out of date, and the website docs date from 2016, yet two new release versions have been tagged on Github.  Are we just supposed to read the source code now?

**Comment by BoPeng** [comment]
I re-generated all the rst files and put them all under the [docs](https://github.com/BoPeng/simuPOP/tree/master/docs) directory. The simuPOP doc is now on  https://simupop.readthedocs.io. There are missing pictures or broken links but the documentation is mostly readable. I will update the website to point to these docs when they are ready.

**Comment by BoPeng** [comment]
http://bopeng.github.io/simuPOP/ looks much better so I will use github.io instead of readthedocs.
