### ISSUE TITLE
How to show generation of every individual in a simulation

### ISSUE THREAD

**Issue by rogerdoyle** [BoPeng/simuPOP#29]
Hi, Bo:
I wonder if you could suggest a way to include the population variable "gen" in the information fields of individuals? 

I'm simulating very small populations (less than 100) for not more that 50 generations, with randomly varying subpopulation sizes and sporadic migration among subpopulations. 

The desired output is a complete pedigree for the whole simulation including genotype of every animal. The problem is that stochastic variation in population size makes it hard to figure out what generation each animal belongs to.

What I'm aiming for is a standard output file with variables like this:

"ID", "Sire", "Dam", "Sex", "Generation" , [genotypes]

Below is a simplified version of the program (sans random census variability and migration), stripped of all statistical calculations. The output is sent to the screen and also to a file named "simp_pedigree.ped".

You can see that function gentag(gen) assigns "gen" to variable "gen_id". However, I can never get gen_id to appear in output.

It appears I'm not understanding how information can be transferred from population class to individual class OR I'm not specifing output correctly. Or, probably, both.

Hope you can help.

Roger. 

```
#---- generation_id_puzzle.py

from simuPOP import *
import simuPOP as sim
gen_evolve=20 #gens of evolution and retention
#there are 4 different population sizes during evolution

def censuscontrol(gen):
    if gen>=10 and gen<13:
        return [10,20]
    elif gen>=13 and gen<15:
        return [20,40]
    elif gen==15:
        return [22,44]
    else:
        return [30,60]
def gentag(gen):
    gen_id=gen
    return gen_id

pop = sim.Population(size=[8,16], ploidy=2, loci=[0,1,2], infoFields=['gen_id', 'ind_id', 'father_id', 'mother_id'],
        lociPos = (1, 2, 3),  #three loci on 3 different chromosomes 
        ancGen=gen_evolve)  
pop.evolve(
	initOps=[
            sim.IdTagger(begin=0, end=-1),
	    sim.InitSex(maleProp=0.5),
            sim.InitGenotype(freq=[0.2, 0.2, 0.2, 0.2, 0.2], loci=[0,1,2]), #five alleles at three loci
            sim.PedigreeTagger(output='>>simp_Pedigree.ped', outputLoci=[0,1,2]) #outputs to file
            #sim.PedigreeTagger(output='>>simp_Pedigree.ped', outputFields=[gen_id], outputLoci=[0,1,2]) #crash gen_id not defined
            #sim.PedigreeTagger(output='>>simp_Pedigree.ped', infoFields=[gen_id],o utputLoci=[0,1,2]) #crash gen_id not defined
            ], #end of initOps
        preOps=[
            ],
        matingScheme=sim.MonogamousMating(subPopSize=censuscontrol,numOffspring=8, sexMode=(sim.NUM_OF_MALES, 2),
	ops=[
            sim.MendelianGenoTransmitter(),
            sim.IdTagger(),
            sim.PedigreeTagger(output='>>simp_pedigree.ped', outputLoci=[0,1,2]),
            ], #end of Ops
        ), #end of matingScheme   
	gen = gen_evolve,
    ) #end of pop.evolve

#Pedigree info sent to the monitor
print '\nComplete pedigree and genotype information (except generation)'
print "gen_id, ID, Sire, Dam, Sex, Affection, Loc1, Loc2 Loc3"  #gen_id not shown
print(open('simp_pedigree.ped').read()) #gen_id not shown
```

**Comment by BoPeng** [comment]
The script is messed up, could you use attachment?

**Comment by rogerdoyle** [comment]
Hi Bo, sorry, I've attached the working py file with extension changed to txt. 

[generation_id_puzzle.txt](https://github.com/BoPeng/simuPOP/files/756062/generation_id_puzzle.txt)

**Comment by BoPeng** [comment]
You can use `InfoExec` to assign `gen_id` from `gen` (population variable), and output this info using parameter `outputFields` of `PedigreeTagger`.

```
            sim.InfoExec('gen_id = gen'),
            sim.PedigreeTagger(output='>>simp_pedigree.ped', outputLoci=[0,1,2], outputFields=['gen_id']),
```

`gene_id` is the column after `U`.

**Comment by rogerdoyle** [comment]
Worked perfectly!
Thanks Bo. Roger.
