### ISSUE TITLE
Showing subPop membership of individuals in a pedigree

### ISSUE THREAD

**Issue by rogerdoyle** [BoPeng/simuPOP#30]
Hi, Bo:

Thanks for the advice on identifying the generation of every individual. Now I'm trying identify the subPopulation membership of every individual, following the same approach (sim.InfoExec statement that defines a variable "sp_id"). As far as I can tell the syntax is acceptable to simuPOP but the output value of sp_id is "0" for every individual. There are indeed two subpopulations in the simulation.

Can you check to see what I've got wrong?

Thanks and regards. Roger

(attached file  "subPop_id_puzzle 08FE17" is py formatted with txt extension)

[subPop_id_puzzle 08FE17.txt](https://github.com/BoPeng/simuPOP/files/762185/subPop_id_puzzle.08FE17.txt)

**Comment by BoPeng** [comment]
Gen is a population variable (same for everyone) and can be assigned to individuals using  InfoExec, subpopulations IDs are different and can be assigned using population function setIndInfo. The operator would be something like PyOperator(lambda pop: ［pop.setIndInfo("spid", x , subpopulations=x) for x in range(pop.numSubpop)］is not None)

**Comment by BoPeng** [comment]
Note that this method, when combined with `migrate_to` set by a `Migrator`, is frequently used to track migrants.

**Comment by rogerdoyle** [comment]
Hi, Bo, 
I've tried mightily to get your suggested solution to work but have been unable to do so. It is probably too general for my limited knowledge of python and its naming conventions such as when, in an explanation or example, is a name referring to an actual python/simuPOP object and when is it being used as a placeholder to be replaced by the author of the actual script. Anyway, I'll keep working on it and let you know. Thanks again, simuPOP is a beautiful program. Roger.

**Comment by BoPeng** [comment]
Sorry Roger, I was on the road and had to be brief. The working code using your previous example would be

```python
from simuPOP import *
import simuPOP as sim
gen_evolve=20 #gens of evolution and retention
#there are 4 different population sizes during evolution

def censuscontrol(gen):
    if gen>=10 and gen<13:
        return [10,20]
    elif gen>=13 and gen<15:
        return [20,40]
    elif gen==15:
        return [22,44]
    else:
        return [30,60]
def gentag(gen):
    gen_id=gen
    return gen_id

pop = sim.Population(size=[8,16], ploidy=2, loci=[0,1,2], infoFields=['gen_id', 'ind_id', 'father_id', 'mother_id', 'spid'],
        lociPos = (1, 2, 3),  #three loci on 3 different chromosomes 
        ancGen=gen_evolve)  
pop.evolve(
	initOps=[
            sim.IdTagger(begin=0, end=-1),
	    sim.InitSex(maleProp=0.5),
            sim.InitGenotype(freq=[0.2, 0.2, 0.2, 0.2, 0.2], loci=[0,1,2]), #five alleles at three loci
            sim.PedigreeTagger(output='>>simp_Pedigree.ped', outputLoci=[0,1,2]) #outputs to file

            # 
            #sim.PedigreeTagger(output='>>simp_Pedigree.ped', outputFields=[gen_id], outputLoci=[0,1,2]) #crash gen_id not defined
            #sim.PedigreeTagger(output='>>simp_Pedigree.ped', infoFields=[gen_id],o utputLoci=[0,1,2]) #crash gen_id not defined
            ], #end of initOps
        preOps=[
            PyOperator(lambda pop: [pop.setIndInfo(x, "spid", x) for x in range(pop.numSubPop())] is not None),
            ],
        matingScheme=sim.MonogamousMating(subPopSize=censuscontrol,numOffspring=8, sexMode=(sim.NUM_OF_MALES, 2),
	ops=[
            sim.MendelianGenoTransmitter(),
            sim.IdTagger(),
            sim.InheritTagger(infoFields='spid'),
            sim.PedigreeTagger(output='>>simp_pedigree.ped', outputLoci=[0,1,2], outputFields=['spid']),
            ], #end of Ops
        ), #end of matingScheme   
	gen = gen_evolve,
    ) #end of pop.evolve

#Pedigree info sent to the monitor
print('\nComplete pedigree and genotype information (except generation)')
print("gen_id, ID, Sire, Dam, Sex, Affection, Loc1, Loc2 Loc3")  #gen_id not shown
print(open('simp_pedigree.ped').read()) #gen_id not shown
```

The most tricky part can be the use of `InheritTagger`, what is happening is that

1. We use `PyOperator` with `setIndInfo` to set subpopulation ids to individuals' `spid` field before mating. These are **parents**
2. We use `InheritTagger` to pass `spid` from parents to offspring during mating, before `PedigreeTagger` so that the offspring has this info and can be outputted by `PedigreeTagger`.

I hope this is conceptually clear so that you can adapt this method to your code.

**Comment by rogerdoyle** [comment]
Great! Most helpful. Here is code that records all of: id, parentage, generation, subpopulation and genotype of all individuals in the simulation, including the founders. (This is case someone else wants to simulate what  happens in small populations that violate every one of the Fisher-Wright assumptions.)
Roger.
[Simple 2pop id gen and subpop tags 09FE17.txt](https://github.com/BoPeng/simuPOP/files/765296/Simple.2pop.id.gen.and.subpop.tags.09FE17.txt)

**Comment by BoPeng** [comment]
I just moved all examples to [simuPOP-examples](https://github.com/BoPeng/simuPOP-examples/) and will use this repository to maintain all examples. If you have some free time, could you add your script (and a `README.md` to [contrib/Roger](https://github.com/BoPeng/simuPOP-examples/tree/master/contrib)? Briefly speaking, you would need to fork the repository, add the files, and submit a pull-request.
