### ISSUE TITLE
Honor or warn about unused parameter subPops of standalone HomoMating scheme

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#33]
This is related to #32 

`HomoMating` applies to all subpopulations when it is used by itself. It makes uses of parameter `subPops` and can be applied to only specified (virtual) subpopulations when it is used within a `HeteroMating` mating scheme. This is well-documented but users might still use parameter `subPops` and expect the `HomoMating` mating scheme to be applied to selected virtual subpopulations.

We should either honor this parameter or warn users when a standalone `HomoMating` is used with non-`ALL_AVAIL` subPops. Technically speaking (and on simuPOP's defense), this was not implemented partly because it was not easy to tell if a `HomoMating` is used alone or within a `HeteroMating` (in which case `subPops` is actually handled by `HeteroMating`). It is now possible to do it with c++11's `type_trait`, and without the need to support Python 2 and all the ancient compilers.

**Comment by ashander** [comment]
It makes sense that it's hard to know where the object is used (but very cool that c++11 makes this possible).

At the least, a warning (maybe something similar to [the type done here](https://github.com/BoPeng/simuPOP/blob/aa3b7440368906755982bd5491329fa1cf15f069/src/mating.cpp#L1624)) when using `subPops=` in a standalone `HomoMating`, could help users who like me failed to parse the docs correctly.

**Comment by BoPeng** [comment]
So it was done in some places, but using `dynamic_cast` was a bad idea according to [this stackflow discussion](http://stackoverflow.com/questions/500493/c-equivalent-of-instanceof). It makes sense for `HomoMating` to accept this parameter but things can get complicated with `ConditionalMating`, nested `HeteroMating` etc. Also, getting C++11 to work for all platforms is non-trivial.

**Comment by petrelharp** [comment]
Suggestion: by my reading, these two distinct uses of `HomoMating` should perhaps be different functions.
