### ISSUE TITLE
With more than 500 loci, recombinations occur past the last locus

### ISSUE THREAD

**Issue by petrelharp** [BoPeng/simuPOP#37]
If `len(lociPos)` is `n` then we expect in the output of `Recombinator` that the "loci after which recombination events happens" (from [the docs](http://simupop.sourceforge.net/manual_svn/build/refManual_ch3_sec5.html#Recombinator.Recombinator))  to all be between `0` and `n-1` (and write code that depends on this...).  This seems to be what happens *unless* the number of loci is more than 500, in which case a certain number of these loci will be equal to `n` as well.

Here is a MWE:
```
import simuPOP as sim

sim.setOptions(seed=123)

for nloci in [200, 400, 500, 501, 800, 900]:
    locus_position = [k/nloci for k in range(nloci+1)]
    generations = 30
    popsize=20

    pop = sim.Population(
            size=[popsize],
            loci=[len(locus_position)],
            lociPos=locus_position,
            infoFields=['ind_id'])

    pop.evolve(
        initOps=[sim.InitSex(), sim.IdTagger()],
        matingScheme=sim.RandomMating(
            ops=[
                sim.IdTagger(),
                sim.Recombinator(intensity=5.0,
                                 output=">>"+str(nloci),
                                 infoFields="ind_id")
            ]),
        gen=generations
    )
```

With that file as `debug_recomb.py`, run
```
python3 debug_recomb.py
for x in *; do echo "$x ---------"; cut -f 4- -d ' ' $x | grep $x; done
```
and observe that no such loci are observed for numbers of loci up to 500, but are for numbers 501 and above.

**Comment by BoPeng** [comment]
Why do you use range(nLoci + 1)? This produces nLoci + 1 loci.

**Comment by petrelharp** [comment]
Hm, yes, you are right. That makes it even stranger - the bad behavior kicks in at 502 loci.  

The problem was a bad name: I should have done
```
for nloci in [200, 400, 501, 502, 800, 900]:
    locus_position = [k/(nloci-1) for k in range(nloci)]
```
The reason I did it this way is that I wanted a locus at 0.0 and another at 1.0.

Still - something is not right here, or at least not consistent between small and large numbers of loci.  Am I right that if it outputs `k`, that means there was a recombination between the `k`th and `k+1`th loci, which are zero-indexed?  So, with three loci, there are two spaces, so the numbers should all be `0` and `1`?  (which is what happens if the number of loci below 502)

**Comment by BoPeng** [comment]
I cannot reproduce what you have experienced. In your initial report,

```
 cut -f 4- -d ' ' $x | grep $x; done
```

produce `500` because you had 501 loci. If you adjust the code to `range(nLoci)`, do you still see the same problem?

**Comment by petrelharp** [comment]
Here is modified code:
```
import simuPOP as sim

sim.setOptions(seed=123)

for nloci in [200, 400, 501, 502, 800, 900]:
    locus_position = [k/(nloci-1) for k in range(nloci)]
    generations = 30
    popsize=20

    pop = sim.Population(
            size=[popsize],
            loci=[len(locus_position)],
            lociPos=locus_position,
            infoFields=['ind_id'])

    pop.evolve(
        initOps=[sim.InitSex(), sim.IdTagger()],
        matingScheme=sim.RandomMating(
            ops=[
                sim.IdTagger(),
                sim.Recombinator(intensity=5.0,
                                 output=">>"+str(nloci),
                                 infoFields="ind_id")
            ]),
        gen=generations
    )

print("Now run")
print("for x in *; do echo \"$x ---------\"; cut -f 4- -d ' ' $x | grep $((x-1)); done")
```
... and my output:
```
(tortoisim) peter@skua:~/debug/simuPOP$ python3 debug_recomb.py 
simuPOP Version 1.1.8.3 : Copyright (c) 2004-2016 Bo Peng
Revision 4553 (Feb 11 2017) for Python 3.5.3 (64bit, 1thread)
Random Number Generator is set to mt19937 with random seed 0xf83ff94e4cf7e511.
This is the standard short allele version with 256 maximum allelic states.
For more information, please visit http://simupop.sourceforge.net,
or email simupop-list@lists.sourceforge.net (subscription required).
Now run
for x in *; do echo "$x ---------"; cut -f 4- -d ' ' $x | grep $((x-1)); done
(tortoisim) peter@skua:~/debug/simuPOP$ for x in *; do echo "$x ---------"; cut -f 4- -d ' ' $x | grep $((x-1)); done
200 ---------
400 ---------
501 ---------
502 ---------
209 234 326 368 374 501
342 373 501
178 214 310 403 501
75 165 200 214 325 403 414 451 501
56 59 65 163 201 298 377 398 501
1 48 334 428 501
11 103 350 438 501
39 391 401 472 490 501
73 102 309 501
211 324 501
78 345 352 386 426 501
84 274 324 337 403 486 501
36 41 69 123 301 309 471 501
126 184 210 257 367 386 501
127 288 432 501
800 ---------
268 330 358 531 735 799
123 435 467 502 739 799
21 264 310 311 550 799
90 114 605 706 799
389 489 552 676 760 799
184 534 591 674 799
900 ---------
254 309 473 824 899
87 325 800 850 865 889 899
372 420 477 550 899
99 171 213 899
debug_recomb.py ---------
bash: debug_recomb.py: syntax error: invalid arithmetic operator (error token is ".py")
```

Since I am setting the seed, you should get the same output, I believe?

**Comment by BoPeng** [comment]
I can reproduce your problem now. The magic happens at `n=500` because with your `intensity=5`, the recombination rate is `1/500*5=0.01` at n=500, which hits a magic value that simuPOP uses a different algorithm for rare and common recombination events ([code](https://github.com/BoPeng/simuPOP/blob/master/src/transmitter.cpp#L723)). it is late so I will have a look at the output tomorrow but it is likely that one of the algorithms fail to report recombination event at the last location.

**Comment by BoPeng** [comment]
It is painful to revisit that single most complicated piece of code in simuPOP .... 

It turns out that using a geometric recombination algorithm for uniform rare recombination rate, the last recombination event can happen right after the last locus, which is considered to be a valid event although it does not recombine anything.

I have submitted a patch to fix this problem. Please either manually remove the reported recombination event at the end of chromosome or compile simuPOP from source.

**Comment by BoPeng** [comment]
Hold on, my patch did not pass unit tests. I was not joking in saying this is the most complicated piece of code.

**Comment by petrelharp** [comment]
Thanks for looking into it, and good luck...

**Comment by BoPeng** [comment]
OK, the second patch fixed the first one so you are good to go.

Again, the problem was caused by reporting of fake recombination events at the end of chromosomes so there is nothing wrong with recombination itself. You can simply ignore those events or compile simuPOP from source.

**Comment by petrelharp** [comment]
Awesome, thanks.
