### ISSUE TITLE
Migration operator

### ISSUE THREAD

**Issue by dbailleul** [BoPeng/simuPOP#44]
Good afternoon,
Sorry for this question, but just to be sure, is operator `Migrator` equivalent to `migrIslandRates` ?
For example, the argument:
```
preOps=sim.Migrator(rate=[
    [0,0.0001],
    [0.0001,0]
    ],
mode=sim.BY_PROPORTION)
```
could correspond to a island model migration, isn't it ?
Thanks for the answer !
Sincerely

**Comment by BoPeng** [comment]
No, `migrIslandRates` etc are function to generate proper migration matrixes from such models and in the end you will need to do something like `sim.Migrator(rate=migrIslandRates(...`.

Note that for your particular example, with `BY_PROPORTION and `0.0001`, there would be no migration for small populations.

**Comment by dbailleul** [comment]
Thanks for answering so quickly !
But if with Migrator, we set the same migration rate for both
subpopulations (as in my exemple, 0.0001), isn't it the same principle as
with migrIslandRates(0.0001, 2) ?

PS : thanks, my Ne is 100.000 !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-08 15:00 GMT+01:00 Bo <notifications@github.com>:

**Comment by BoPeng** [comment]
Yes. They are the same. You can print the result of `migrIslandRates(0.0001, 2)` to confirm.

**Comment by dbailleul** [comment]
Thanks a lot !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-08 15:37 GMT+01:00 Bo <notifications@github.com>:
