### ISSUE TITLE
Is it possible to suppress output from a `CSVExporter`?

### ISSUE THREAD

**Issue by ashander** [BoPeng/simuPOP#45]
Exporting will write lines like `Exporting....1....2....3....4....5....6....7....8....9.... Done.` to standard out.

From the `simuOpt` help for `gui=`,
 the [definition of `.ProgressBar()`](https://github.com/BoPeng/simuPOP/blob/dfad26ead4ce5a5f3bb8a5f67fe226e9caaef19d/src/utils.py#L667-L693), and [these lines in `.Exporter()`](https://github.com/BoPeng/simuPOP/blob/dfad26ead4ce5a5f3bb8a5f67fe226e9caaef19d/src/utils.py#L2442) it does not seem possible to suppress these. In small tests I also haven't been able to find a combination of options that will suppress the output.

**Comment by BoPeng** [comment]
Cannot recall the details but did you try `gui='batch'`?

**Comment by ashander** [comment]
Aha! Thanks that works, which I should've seen from the code I linked :)

I think I didn't try it because the [help for that parameter [in `simuOpt`](https://github.com/BoPeng/simuPOP/blob/cd2d75ec9070be245f7d902f34a80f9b80795a15/simuOpt.py#L169-L171) read to me as if it will work as default. Which I thought was a graphical GUI (same as `gui=None').
