### ISSUE TITLE
How works gen/step with pop.evolve ?

### ISSUE THREAD

**Issue by dbailleul** [BoPeng/simuPOP#46]
Thanks again and again for simuPOP !

I thought I understand right how gen and step arguments work and I ran some short simulations.
I'm not sure anymore.

Let's take one of simuPOP exemple:

_>>> import simuPOP as sim
>>> pop = sim.Population(size=1000, loci=2)
>>> pop.evolve(
...     initOps=[
...         sim.InitSex(),
...         sim.InitGenotype(genotype=[1, 2, 2, 1])
...     ],
...     matingScheme=sim.RandomMating(ops=sim.Recombinator(rates=0.01)),
...     postOps=[
...         sim.Stat(LD=[0, 1], step=10),
...         sim.PyEval(r"'%.2f\n' % LD[0][1]", step=10),
...     ],
...     gen=100
... )
0.25
0.22
0.21
0.19
0.17
0.15
0.15
0.12
0.10
0.10
100L_

If we asked to simuPOP to print also the gen number for each result, it would have been (I suppose):
0 0.25
10 0.22
20 0.21
30 0.19
40 0.17
50 0.15
60 0.15
70 0.12
80 0.10
90 0.10
And thus, as Python starts with 0 instead of 1, the number of the run would be:
run 1 (gen 0) - run 11 (gen 10) - run 21 (gen 20) - 31 - 41 - 51 - 61 - 71 - 81 - run 91 (gen 90)

So we run 100 generations, but we don't have the results for gen 100 because the program stopped at run 100 (gen 99).

So, first, if I want to have the results for gen 100 with a step of 10, I have to set **gen = 101**, am I right ? 
And second, gen 0 is in fact "gen 1", i.e. the population evolves for 1 generation from the initial state and then the computation is done ?

Thanks in advance for the clarifications.

**Comment by BoPeng** [comment]
There can be less confusion if you think of "pre-evolution" and "post-evolution" generation numbers. Basically, you start from generation 0 pre-evolution. You evolve once and you arrive at generation 0 post-evolution == generation 1 pre-evolution. You evolve 100 generations and you arrive at generation 99 post-evolution == generation 100 pre-evolution. With `step=10`, the operator should run at generation 0, 10, 20, etc, so you indeed need `gen=101` to get it execute at generation `100`.

**Comment by BoPeng** [comment]
Note that, however, if you really need to skip generation 0 and execute **after** every 10 generations, you can do something like

```
begin=-91, step=10
```
to execute the operator at the end of (if specified inside `postOps`) generation `9`, `19`, ..., `99`.
