### ISSUE TITLE
Calculating and saving average heterozygosity for each generation

### ISSUE THREAD

**Issue by SMartinOSU** [BoPeng/simuPOP#48]
Hello, 
   I've been trying to model the rate of potential changes in the average heterozygosity in small populations, and simuPOP seems like a wonderful module to do this. However, due to my unfamiliarity with python, I've been having trouble getting the final output I would like. Ideally, I want to run through multiple generations and save the overall average heterozygosity across all chromosomes per generation. I'm at a point where I can get heterozygosity for any one loci, but I've been getting errors with everything I've tried to calculate the average. I'm also like to print out the averages into a csv file (to make importing the estimates into R much easier down the road), but I don't know what to edit to get it to only give me the single value per generation. 95% of my code basically comes from various simuPOP examples, and I'm probably just missing a simple answer here, but I would appreciate any help or advice. 

Again, thank you for any help,
-Scott

Current code:
```
import simuPOP as sim
import simuPOP.utils as u
import numpy as n
import random


def avgHet(pop, lociNum):
#this is what I've been trying to use to get the average heterozygosity and where the problem is
      avgHet = {},
      sim.Stat(heteroFreq=sim.ALL_AVAIL, step=1),
      for i in range(lociNum):
         avgHet.append = pop.dvars().heteroFreq[i].values()
      pop.dvars().avgHet = n.mean(avgHet)
      return True

def simuOverlappingGeneration(size, maxAge, minMatingAge, maxMatingAge, gen):
    '''
    size         population size.
    maxAge       maximum age. individuals with age > maxAge will die.
    minMatingAge minimal mating age.
    maxMatingAge maximal mating age.
    gen          generations to simulate
    '''
    pop = sim.Population(size, loci=[2]*10, infoFields=['age'])
    pop.setIndInfo([random.randint(0, maxAge) for x in range(size)], 'age')
    pop.setVirtualSplitter(sim.InfoSplitter('age',
        cutoff=[minMatingAge, maxMatingAge + 0.1, maxAge + 0.1]))
    pop.evolve(
        initOps = [
            sim.InitSex(),
        	 sim.InitGenotype(freq=[0.19, 0.81]),
        	 sim.Stat(effectiveSize=sim.ALL_AVAIL, subPops=[(0,0), (0,1), (0,2), (0,3)],
            vars='Ne_temporal_base')
        ],
        preOps = sim.InfoExec('age += 1'),
        matingScheme = sim.HeteroMating(
            [sim.CloneMating(subPops=[(0, x) for x in (0, 1, 2)], weight=-1),
            sim.RandomMating(subPops=[(0, 1)])]),
        postOps = [
        sim.PyOutput('\n', reps=-1, step = 1),
		  sim.Stat(heteroFreq=sim.ALL_AVAIL, step=1),
        sim.PyEval(r"'Gen: %d, HeteroFreq: %.2f\n' % (gen, heteroFreq[10])", step=1),
        sim.PyEval(r'"Generation=%d\n" % gen', output='>>test.txt'),
        u.Exporter(format='csv', output='>>test.txt'),
        avgHet(pop, 10)
        ],
        gen = gen
    )

simuOverlappingGeneration(50, 10, 3, 9, 5)
```

**Comment by BoPeng** [comment]
If you are unfamiliar with [all the tricks related to parameter `output`](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch5_sec1.html#write-output-of-operators-to-one-or-more-files), the easiest way is to remove all your `PyOperator` and `PyEval` operators, write everything inside your  `avgHet` function and call it with a `PyOperator` operator

```
PyOperator(avghet)
```

You can use regular function calls in this function (`stat` instead of `Stat`, as explained in [function form of operator](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch5_sec1.html#function-form-of-an-operator), with the following information,

1. `sim.stat(pop, heteroFreq=sim.ALL_AVAIL)`, no `step` parameter
2. get `pop.dvars().heteroFreq[i]` from the population, you can print the whole variable and see what they are.
3. Open a file in this function, `open('stat', 'a')` and write statistics in csv format
4. Use `pop.dvars().gen` to get the generation number...

**Comment by SMartinOSU** [comment]
Thank you for your help and advice. I updated the avgHet function I wrote so now it writes out the heterozygosity for each loci for each generation, and I should be able to do the rest through R. I know someone with more experience could write a more elegant solution, but this works for my purpose.

Thanks again for the assistance,
-Scott

For those who may be interested in trying this in the future, my updated code is:


import simuPOP as sim
import random


def avgHet(pop):
      lociNum=10
      sim.stat(pop, heteroFreq=sim.ALL_AVAIL),
      with open('HeteroFreq.txt','a') as f:
          print(pop.dvars().gen, file = f)
      for i in range(lociNum):
          with open('HeteroFreq.txt','a') as f:
              print(pop.dvars().heteroFreq[i], file = f)
      with open('HeteroFreq','a') as f:
          print('', file = f)
      return True

def simuOverlappingGeneration(size, maxAge, minMatingAge, maxMatingAge, gen):
    '''
    size         population size.
    maxAge       maximum age. individuals with age > maxAge will die.
    minMatingAge minimal mating age.
    maxMatingAge maximal mating age.
    gen          generations to simulate
    '''
    pop = sim.Population(size, loci=[1]*10, infoFields=['age'])
    pop.setIndInfo([random.randint(0, maxAge) for x in range(size)], 'age')
    pop.setVirtualSplitter(sim.InfoSplitter('age',
        cutoff=[minMatingAge, maxMatingAge + 0.1, maxAge + 0.1]))
    pop.evolve(
        initOps = [
            sim.InitSex(),
        	 sim.InitGenotype(freq=[0.19, 0.81]),
        	 sim.Stat(effectiveSize=sim.ALL_AVAIL, subPops=[(0,0), (0,1), (0,2), (0,3)],
            vars='Ne_temporal_base')
        ],
        preOps = sim.InfoExec('age += 1'),
        matingScheme = sim.HeteroMating(
            [sim.CloneMating(subPops=[(0, x) for x in (0, 1, 2)], weight=-1),
            sim.RandomMating(subPops=[(0, 1)])]),
        postOps = [
        sim.PyOutput('\n', reps=-1, step = 1),
        sim.PyOperator(avgHet)
        ],
        gen = gen
    )

simuOverlappingGeneration(50, 10, 3, 9, 5)

**Comment by JKHopf** [comment]
Thanks for posting your final code @SMartinOSU! It helped solve a problem I was having with saving an output from a user-defined function in simuPOP.
