### ISSUE TITLE
About mating scheme when simulating

### ISSUE THREAD

**Issue by ecotang** [BoPeng/simuPOP#5]
Hill everyone, 

I'm a novice to simuPOP. I have a basic question, when the simulated species has the gametophytic self-incompatibility (GSI) system (e.g. P1: S1S2 X P2 S2S3, under GSI, the offsprings would be  S1S3 or S2S3). In such case, how should I choose the parameter value to account for GSI and do simulation?

Thank you all very much!
Sincerely Liang Tang

**Comment by BoPeng** [comment]
Suppose `S1S2`, `S2S3` are parental alleles, and complete GSI means offspring can not have `S1S2`? This can be done by a `DiscardIf` during-mating operator that accepts a function that accepts `dad`, `mom` and `off`, and you will need to return `False` for incompatible genotypes.  [This section of the simuPOP documentation](http://simupop.sourceforge.net/manual_release/build/userGuide_ch5_sec12.html#conditional-during-mating-operator-operator-discardif) introduces this usage.

**Comment by ecotang** [comment]
Thank you very much! I'll try.

Liang Tang


在 2016-10-07 13:56:57，Bo <notifications@github.com> 写道：
Suppose S1S2, S2S3 are parental alleles, and complete GSI means offspring can not have S1S2? This can be done by a DiscardIf during-mating operator that accepts a function that accepts dad, mom and off, and you will need to return False for incompatible genotypes. This section of the simuPOP documentation introduces this usage.
