### ISSUE TITLE
simuOpt.Params - deprecated but alternative?

### ISSUE THREAD

**Issue by avabelieve** [BoPeng/simuPOP#50]
As I ran those examples, some of them gave the same error: 
`AttributeError: module 'simuOpt' has no attribute 'Params'`
So I'm wondering what's the alternative to this deprecated module/class.

**Comment by BoPeng** [comment]
`simuOpt.Params` was developed when [`optparge`](https://docs.python.org/2/library/optparse.html) was the only option to handle command line option. Right now [`argparse`](https://docs.python.org/3/library/argparse.html) is generally recommended.

`simuOpt.Params` does provide some unique features, especially the automatic GUI feature that I have not seen in other modules, but it does not worth the trouble to maintain a general purpose argument parser as part of `simuPOP`. I would suggest that you 

1. Take the core functions of the examples and wrap them with `argparse` (without GUI feature)
2. Use Python 2.x version of simuPOP where `simuOpt.Params` is still available but you will have to use Python 2.x and compile simuPOP from source
3. Port `simuOpt.Params` to Python 3 as a separate module if you do like it.
