### ISSUE TITLE
self-incompatibility mating scheme: (set)Genotypes, subPops, VSP, alleleNames, etc.?

### ISSUE THREAD

**Issue by avabelieve** [BoPeng/simuPOP#51]
I'm simulating the mating between male haplotypes (SLFs, F) and female haplotypes (S-RNases, R) under SI, where each SLF can mate with a few S-RNases that genotypically differ from itself, but not all of them. Also, each SLF haplotype has to be able to interact with both diploid R-alleles for the mating to actually happen. (For example, F0 cannot mate w/ R0 as they are the same type; it's predefined here to be able to mate with R1,2,3, but not R4 & 5. So F0 can interact with R1R2 but not R1R4). 

Sorry it's a bit challenging to put down the nitty-gritty of what I'm trying to do, as I'm very new to (population) genetics... I'm thinking to use subPops or VSP for all breedable combinations. Any practical suggestions?

BTW, before came across your simulator I used nested list, dictionaries and nested loops for what I was trying to do. But yours looks far more appealing!

**Comment by BoPeng** [comment]
I am sorry but I am afraid that I do not know what these `SLF`, `S-RNases` mean. if the mating is really selective and complicated, perhaps you can use a `PyMating` scheme to explicitly group individuals and mate them.

**Comment by avabelieve** [comment]
Thanks Bo! 
SLF is the male (pollen) gamete and S-RNases the female (pistil) gamete. 
I haven't been able to find an example of using subPopNames. Thinking to do something like: 
pop.subPopNames('B0', 'B1', 'B2', 'B3'):           # breadable S-Rnase & SLF combinations
    B0 = ['R0', 'F1', 'F3', 'F5', 'F7', 'F9', 'F15']
    B1 = ['R1', 'F0', 'F2', 'F4', 'F7', 'F10', 'F16', 'F18'] 
    B2 = ['R2', 'F1', 'F6', 'F7', 'F9', 'F13', 'F17', 'F19']
    B3 = ['R3', 'F1', 'F2', 'F8', 'F10', 'F16', 'F18', 'F19']

Then in calling HomoMating, according to the documentation: 
matingScheme = HomoMating(chooser*****, generator**, subPopSize=[<does a list of floats fit here>], subPops=ALL_AVAIL, weight=0)
* - syntax: Do you have an example of using parentsGenerator?>, 
** - how does generator differ from chooser? 

Things I learned so far from the documentation seem highly fragmental and hard to be consolidated. After going through the example PyParentChooser it still hasn't clicked... 

Sorry for another convoluted question!

**Comment by BoPeng** [comment]
> How does generator differ from chooser?

Conceptually, **parent choosers** are responsible for picking single parents (asexual mating) or pairs of parents from parental populations. A number of predefined parent choosers have been defined to, for example, pick a random male and a random female. After parents are chosen **offspring generators** are responsible for producing one or more offspring from the parents by inheriting genotypes and sometimes phenotypes from the parents.

> podParentsChooser 

If you are referring to [this example](http://simupop.sourceforge.net/Cookbook/PythonParentChooser), `podParentsChooser` is a [generator function](https://www.learnpython.org/en/Generators) that `yield` pairs of parents one by one. This feature is documented [here](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch6_sec3.html#a-python-parent-chooser) but you should probably read the entire chapter to understand it.

**Comment by avabelieve** [comment]
Thank you Bo! The [documentation](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch6_sec3.html) was helpful. 

Where can I find the source code of sim.Population? I don't understand how those numbers for 'father_idx' and 'mother_idx' were generated even after printing them out...

**Comment by BoPeng** [comment]
sf.net is down. I should really move simuPOP website to github.io.

The source code of everything is at [github repo](https://github.com/BoPeng/simuPOP/tree/master/src). `father_idx` and `mother_idx` are the indexes of parents in the parental population. So if you dump the parental population, you can locate parents using these indexes.

**Comment by avabelieve** [comment]
What does replications do in class Simulator? I was expecting that all the replications within each generation/step would add up to 1, which is not the case. 

Also in evolve, what does the list of genotype ` [0, 1, 1, 0] ` stand for as in InitGenotype(genotype=[0, 1, 1, 0])? (a, A, B, b)? It came from example [selfing.py](https://github.com/BoPeng/simuPOP-examples/blob/master/examples/selfing.py)

**Comment by BoPeng** [comment]
Replicates are, well, replicates. It allows you to, for example, clone an initial population multiple times, evolve them together. You can think of them as multiple independent evolving populations, but `rep` allows you to get and summarize statistics from multiple replicates easily.

simuPOP genotypes are numbers and it is up to you to define their meanings. For example they can be wildtype and mutant in binary module (0, 1), or `ACGT` or `AGTC` in short module depending on option `alleleNames`, or `100`, `101`, etc if you are modeling the evolution of microsatellite markers.

**Comment by avabelieve** [comment]
So the purpose to use replicates is to increase the number of samples? So each time a different effective population is selected?

And only binary code can be used to identify simuPOP genetypes but not letters/strings, correct?

**Comment by avabelieve** [comment]
How would this book help to solve the aforementioned problem? 
_Forward-Time Population Genetics Simulations: Methods, Implementation, and Applications_

**Comment by BoPeng** [comment]
The simuPOP documentation has all the information you need. The book just organize it in some different ways with some more examples. [this page](https://github.com/BoPeng/simuPOP-examples/tree/master/wiley_book) has all the examples from the book though.

**Comment by avabelieve** [comment]
Bo you are the best!!!
