### ISSUE TITLE
python parentchooser_ lighter version

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#53]
Dear Simupop developers and users,
I would like to thank you for maintaining and updating the  mailing list.
I am trying to use parent chooser for selecting random  parents for a forward simulations on wild lion populations.
I  have based the basic of  my script on the provided template embedded below.
The issue is that in the lion population that I am simulating each females- of course not males- after getting impregnated by a male need to be removed from the population.
My main question is regarding the expression
```
yield m, females[rank][randint(0, len(females[rank]) - 1
```
Ideally, I intend to remove individual `females[rank][randint(0, len(females[rank])- 1 `
from `females[ ]` after each iterations such that the impregnated individual are removed for the rest of  iterations `while True `.

I used all of my limited python knowledge about the lists to remove the individual but it seems that the female[ ]  inside sim has specific properties that doesn't allow me to do that.
I also used polyparent chooser, but not having the option replacement=false made this option less optimal in my case.
I appreciate your recommendation to go forward with simulations.
Thanks in advance

```
import simuPOP as sim
from random import randint


def randomChooser(pop, subPop):
    maleChooser = sim.RandomParentChooser(sexChoice=sim.MALE_ONLY)
    maleChooser.initialize(pop, subPop)
    females = []
    # identify females in each social rank
    for rank in range(3):
        females.append([x for x in pop.individuals(subPop) \
            if x.sex() == sim.FEMALE and x.rank == rank])
    # Untill I get return as false : (any females in the same rank/)
    while True:
        # choose a random male
        m = maleChooser.chooseParents()[0]
        rank = int(m.rank)
        print(rank)
        print female[rank].keys()
       
       
        # find a female in the same rank
       
        yield m, females[rank][randint(0, len(females[rank]) - 1)]
       


def setRank(rank):
    'The rank of offspring can increase or drop to zero randomly'
    # only use rank of the father
    return (rank[0] + randint(-1, 1)) % 3

pop = sim.Population(size=[1000, 2000], loci=1, infoFields='rank')
pop.evolve(
    initOps=[
        sim.InitSex(),
        sim.InitInfo(lambda : randint(0, 2), infoFields='rank')
    ],
    matingScheme=sim.HomoMating(
        sim.PyParentsChooser(randomChooser),
        sim.OffspringGenerator(ops=[
            sim.MendelianGenoTransmitter(),
            sim.PyTagger(setRank),
            ])
    ),
    gen = 5
) 
print("I am done")
```
Regards
Arsalan Emami-Khoyi

**Comment by BoPeng** [comment]
There are a number of ways to do this, and the simplest one might be just shuffle the females in advance and return them one by one, something like:

```
import random
...

    for rank in range(3):
        females.append([x for x in pop.individuals(subPop) \
            if x.sex() == sim.FEMALE and x.rank == rank])
        # shuffle females
        random.random_shuffle(females[-1])
    female_indexes = [0]*3 
    while True:
        # choose a random male
        m = maleChooser.chooseParents()[0]
        rank = int(m.rank)
        print(rank)
        print female[rank].keys()
       
       
        # find a female in the same rank
        f = females[rank][female_indexes[rank]]
        female_indexes[rank] += 1
        yield m, f
       
```
Of course you will also need to handle cases when all females have been chosen (`female_indexes[rank]` out of range).

**Comment by arsalane1978** [comment]
Dear Bopeng,
Thank you for your response,
Sorry for the silly question:
You created a list as 
females_indexes = [0 ] *3 >>>>[0,0,0] ?
But how did you populate the list?
Also I see you  have reshuffled only the last element of females by adding (_1)  I am struggleling  to understand the reason.
Many thanks in advance

**Comment by BoPeng** [comment]
Dear Bopeng,
Thank you for your response,
Sorry for the silly question:
You created a list as
females_indexes = [0 ] *3 >>>>[0,0,0] ?
But how did you populate the list?
Also I see you have reshuffled only the last element of females by adding (_1) I am struggleling to understand the reason.
Many thanks in advance

**Comment by BoPeng** [comment]
`[0]*3` is equivalent to `[0,0,0]`.

The for look creates `[[females with rank 0]]`, `[[females with rank 0], [females with rank 1]]` and `[[females with rank 0], [females with rank 1], [females with rank 2]]` step by step so within the loop the last item is the newest one to be shuffled.
