### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by Hadron74** [BoPeng/simuPOP#57]
Hi Bo,

I could not find your Email, so I post it here.
Currently, I use simuPOP in Jupyter Notebook. However when I
"import simuPOP"
there is a error:
"The kernel appears to have died. It will restart automatically."
what happens, could you help me to fix it? Thanks a lot.

Hongchao Lu

**Comment by Hadron74** [comment]
Linux in AWS. Only Jupyter Notebook notwork. Regular Python Prompt is OK.
~Hongchao

[ec2-user@ip-54-40-185-136 ~]$ conda list simupop
# packages in environment at /root/anaconda2:
#
simupop                   1.1.7                    py27_0    bpeng
[ec2-user@ip-54-40-185-136 ~]$ conda list jupyter
# packages in environment at /root/anaconda2:
#
jupyter                   1.0.0                    py27_4
jupyter_client            5.0.1                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0

![image](https://user-images.githubusercontent.com/7869099/43384245-028344e8-9410-11e8-8870-20b593842c30.png)

**Comment by BoPeng** [comment]
I do not have AWS/Linux to test but simuPOP for python2 is no longer supported. Perhaps you can try the python3 version? This version can be installed directly from conda and has been most widely used.

**Comment by BoPeng** [comment]
Please try the new conda releases.
