### ISSUE TITLE
get subPop index or name from individual reference

### ISSUE THREAD

**Issue by nclowell** [BoPeng/simuPOP#58]
Is there a way to retrieve subpop name or index from an individual object?

I would like the subpop name or index to serve as a parameter within a PySelector function. I haven't seen a method for getting the subPop index or name from an individual object, e.g., `individual.subPopName()` or `individual.subPopIndex()`, in the manual. So far, I've been using if-statements to determine the subpop index (see below for example), but even then, this doesn't seem to work predictably for me. Within the PySelector function, it appears to be working. However outside the function, when testing the validity of this method, I find that the if-statement reports an individual as being in all the subpops. Any suggestions? Thank you!

**Example of if-statement for retrieving subpop index:**
```
if ind in pop.individuals(0):
    sp_index = 0
elif ind in pop.individuals(1):
    sp_index = 1
```

**Example of individual in all subpops**

Running:
```
pop = sim.Population(size=[10, 10], loci=1, subPopNames = ['a', 'b'])
individual = pop.individual(0)
if individual in pop.individuals('a'):
    print("yes")
if individual in pop.individuals('b'):
    print("yes")
```

Returns:
```
yes
yes
```

**Comment by BoPeng** [comment]
There is no way to retrieve subpop information from individual objects but you do not really need such information here. All you need to do is to create multiple PySelector operators for different (virtual) sub populations using parameter subPops.

**Comment by BoPeng** [comment]
The in test did not work because these individual objects are not real objects rather than wrappers to pointers to locations of internal structure.

**Comment by nclowell** [comment]
Thank you!
