### ISSUE TITLE
Virtual subpopulations following OutOfAfrica model?

### ISSUE THREAD

**Issue by MrLocuace** [BoPeng/simuPOP#59]
Dear Bo,
I would like to create virtual subpopulations from a single population simulated with the Out of Africa model (let's say, present-day Africans). In the Guide book it says the OutOfAfrica model "merges all subpopulations if it is applied to an initial population with multiple subpopulation". Does this mean that it will merge all virtual subpopulations generated from present-day Africans?. Is there any way I can do it?

Thank you very much

**Comment by BoPeng** [comment]
That sentence basically says that if the initial population consists of multiple subpopulations, the script would merge them into a single ancestral population before evolution.

Virtual subpopulations are NOT subpopulations. They are simply "definitions" so there is no way to merge VSPs. In stead, VSPs will change with the change of the population (merge of subpopulation, change of individual property etc).

**Comment by MrLocuace** [comment]
Thank you, Bo
I forgot to add the "also" in ""Does this "also" mean that it will merge all virtual subpopulations generated from present-day Africans?"".

The initial population would refer in my case to present-day Africans or to the initial population in the OutOfAfrica model?

All the best

**Comment by BoPeng** [comment]
1. No.
2. without referring to the guide, I think initial population means initial population in the OutOfAfrica model.

**Comment by MrLocuace** [comment]
Perfect, thank you very much

**Comment by MrLocuace** [comment]
Dear Bo,
I called the Out of Africa model using the "OutOfAfrica" class and I got the outcome=['AF']. Separately, I set several parameters within a Population object "pop" (e.g., lociPos, number of loci, allele names, pop size, etc). I would like to get allele frequencies for all these loci mimicking genetic variation of 'AF'. I am not sure how to do that. Any suggestion would be welcome. Thank you very much.

**Comment by BoPeng** [comment]
Are you try to get allele frequencies, or trying to get AF similar to real world AF population? For the former, you will need to use the `Stat` operator.

**Comment by MrLocuace** [comment]
Thank you Bo, ideally I would like to get allele frequencies similar to a real world population (e.g. YRI). Then I could chose a particular gene and see how allele frequencies evolve under different virtual subpopulations. All the best

**Comment by BoPeng** [comment]
You will have to start from a real population (e.g. 1000 genomes) to obtain AF similar to real world populations. https://github.com/BoPeng/simuPOP-examples/tree/master/published/simuGWAS has an example for loading HapMap3 population before evolving. Hopefully the example still works.

**Comment by MrLocuace** [comment]
Thank you very much Bo. This is exactly what I need. However, when I run example1.py, I get:

ImportError: No module named selectMarkers

Do you know where can I find that script?. It is not in the simuGWAS directory

Many thanks

**Comment by MrLocuace** [comment]
I found it here:

https://github.com/mossmatters/DPLSim/blob/master/selectMarkers.py

**Comment by BoPeng** [comment]
Yes, that script is supposed to be there but somehow got lost when the repository was migrated to github.

**Comment by MrLocuace** [comment]
The examples run very good !
I would like to ask you another question. When I run example1.py, and expand the init pop to pop size=50000 (scale=5) I get the file ex1_expanded_55.pop. That file has several pop.vars(). For instance, I get "'haploFreq': {(0, 1, 2, 3,...99): {(0, 0, 0, 0,...): 1.0967557963543837e-05, ...Also, there is a haploNum var 'haploNum': {(0, 1, 2, 3,...99): {(0, 0, 0, 0,...):129.0

What do the integers 0-99 mean?
As I understand, you performed the simulations using 5000 loci, therefore I don't think they are loci IDs. On the other hand, the final pop size=50000, I do not think they are individuals. What does "129.0" in haploNum mean?

Thanks very much

**Comment by BoPeng** [comment]
This looks like [this option](https://github.com/BoPeng/simuPOP-examples/blob/master/published/simuGWAS/simuGWAS.py#L65), which causes the use of `haploFreq` option of `Stat` [here](https://github.com/BoPeng/simuPOP-examples/blob/master/published/simuGWAS/simuGWAS.py#L441). So basically the output has haplotype frequency of the first 100 loci. Please refer to [doc](http://simupop.sourceforge.net/manual_svn/build/userGuide_ch5_sec11.html) for details about this option.

**Comment by MrLocuace** [comment]
Dear Bo, thank you very much for your response. I am sorry to bother you again, I have another question. I loaded the population generated by example1.py. I would like to get a sample of this population (e.g. n=500; pop.setVirtualSplitter(sim.RangeSplitter([0, 500]))) and evolve it using as initOps the same sex, genotypes, individuals, male proportions, etc. from that sample. I am not able to find how to do it. Any suggestion would be highly welcome. Thank you very much and all the best

**Comment by MrLocuace** [comment]
Dear Bo, I think the answer to my question is very simple. I just do not need to specify any initOpt after loading the population and creating a VSP. Am I right? Best

**Comment by MrLocuace** [comment]
Hi Bo, thank you for your reply. The structure of the population is the same one produced in the file "ex1_expanded_55.pop" from your paper "Forward-time simulation of realistic samples for genome-wide association studies", example1.py. I just created a VSP taking the first 500 individuals. My question is: if I make this VSP evolve further without specifying any initOpt in pop.evolve, will I have the same initial population structure as that VSP? Thank you very much

**Comment by BoPeng** [comment]
By structure I meant the output of `pop.subPopSizes()`. I do not have a computer at hand but you do not evolve VSP. VSP is just a definition. You need to use `pop.resize()` etc to get your `pop` in shape before evolving it.

**Comment by MrLocuace** [comment]
Thank you very much, Bo
