### ISSUE TITLE
Problem with simuPOP installation

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/simuPOP#6]
Dear all,
I tried to install simuPOP, after an age that I do not use it.
I have a win10 system where I just installed python-2.7.12.msi
(official Python distribution) and python seems to work. I installed
simuPOP-1.1.7.win-amd64-py2.7.exe on a win10 system and I had no
warnings.

However when running very simple scripts I have the following message.

Traceback (most recent call last):
  File "lorenzo.py", line 7, in <module>
    import simuPOP as sim
  File "c:\Python27\lib\site-packages\simuPOP__init__.py", line 323,
in <module>
    from simuPOP.simuPOP_std import *
  File "c:\Python27\lib\site-packages\simuPOP\simuPOP_std.py", line
32, in <module>
    _simuPOP_std = swig_import_helper()
  File "c:\Python27\lib\site-packages\simuPOP\simuPOP_std.py", line
28, in swig_import_helper
    _mod = imp.load_module('_simuPOP_std', fp, pathname, description)
ImportError: DLL load failed with error code 14001

Any help is appreciated. Thanks a lot and sorry, maybe this is  silly
question, but I cannot figure out how to fix it.

Lorenzo

**Comment by BoPeng** [comment]
The windows binary distribution for simuPOP was compiled with windows 7, so I am not surprised that it does not work with windows 10. Because I do not have a windows 10 (virtual) machine at hand, it will take me some time to find one and compile simuPOP. In the meantime, because compiling things under windows is much more complex than other systems, I would suggest that you run simuPOP on a mac or linux machine where a compiler would be readily available.

**Comment by lorenzozane** [comment]
Thank you Bo.
I will change machine then.
Lorenzo

**Comment by BoPeng** [comment]
Could you install http://www.microsoft.com/downloads/details.aspx?familyid=9B2DA534-3E03-4391-8A4D-074B9F2BC1BF&displaylang=en and let me know if this fixes the problem?

**Comment by BoPeng** [comment]
New windows binary (win10, MSVC 2015) will be distributed with the new release of simuPOP.
