### ISSUE TITLE
Begin lineage with loaded population of different alleleType.

### ISSUE THREAD

**Issue by MrLocuace** [BoPeng/simuPOP#62]
Dear Bo,
I would like to ask you a question and I would be very grateful if you could help me.

I loaded a population generated in your paper Peng and Amos BMC Bioinformatics 2010. I would like to evolve this population under a fixed demographic scenario while collecting information from parental and offspring populations. For this, I apparently need to change the alleleType to 'lineage'. However, when I set setOptions(alleleType='lineage', quiet=True) I get this error:

"ImportError: simuPOP has already been imported with allele type short (standard) and cannot be re-imported with allele type lineage. Please make sure you import module simuOpt before any simuPOP module is imported". 

I imported simuOpt before the other modules but I still get that message.

Is it possible to begin a lineage with this loaded population, which can be tracked along their offspring generations?

Thank you very much in advance
Best,
Luc

**Comment by BoPeng** [comment]
The image is module neutral. You can start with the module you want to use and load the image.

**Comment by MrLocuace** [comment]
Thank you for your reply Bo. "Image" is the same as the loaded population?
Best

**Comment by BoPeng** [comment]
By image I meant saved file. It can be saved in a module and loaded in another.  You cannot switch allele type in one python session.

**Comment by MrLocuace** [comment]
Great, thanks Bo

**Comment by MrLocuace** [comment]
Thanks Bo !
