### ISSUE TITLE
No release or tagged versions in Github

### ISSUE THREAD

**Issue by madsenibis** [BoPeng/simuPOP#66]
I see no release versions or tagged versions on Github.  What is the recommended method of checking out and building what you consider to be "1.1.9"?

**Comment by BoPeng** [comment]
conda is the recommended way to install simuPOP 1.1.9 because it provides binary distributions for win/mac/linux. You are right that I should have tagged a release and I am doing it now.

**Comment by madsenibis** [comment]
Thank you!!
