### ISSUE TITLE
ImportError: No module named '_simuPOP_std'

### ISSUE THREAD

**Issue by sasuke79** [BoPeng/simuPOP#78]
I installed SimuPOP 1.1.10 using setup.py on a RHEL 6 system within python 3.5.3. However, whenever I go to import, I get the following:
```
# python3
Python 3.5.3 (default, Mar 28 2017, 13:06:43) 
[GCC 6.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simuPOP
Traceback (most recent call last):
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/site-packages/simuPOP/simuPOP_std.py", line 22, in swig_import_helper
    return importlib.import_module(mname)
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/site-packages/simuPOP/_simuPOP_std.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK5boost9re_detail31cpp_regex_traits_implementationIcE17transform_primaryB5cxx11EPKcS4_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/site-packages/simuPOP/__init__.py", line 322, in <module>
    from simuPOP.simuPOP_std import *
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/site-packages/simuPOP/simuPOP_std.py", line 25, in <module>
    _simuPOP_std = swig_import_helper()
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/site-packages/simuPOP/simuPOP_std.py", line 24, in swig_import_helper
    return importlib.import_module('_simuPOP_std')
  File "/apps/software/gcc-6.2.0/python/3.5.3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_simuPOP_std'
```
Any help with this issue would be appreciated. There were no errors during the install.

Mike

**Comment by BoPeng** [comment]
Do you have boost C++ libraries installed?

**Comment by BoPeng** [comment]
simuPOP used to embed boost 1.49.0 to avoid such problems but now it links to system `boost_regex`, `boost_iostreams`, and `boost_serialization` and there might have been some API change for the `regex` library. Please let me know the version of boost if you have it installed.

**Comment by sasuke79** [comment]
I have 1.55.0, 1.60.0, 1.61.0 on the system. For the build, I used boost 1.61.0.

**Comment by BoPeng** [comment]
I can reproduce your problem with conda 3.5 and boost 1.67. Let me see what went wrong.

**Comment by BoPeng** [comment]
The problem was with different versions of boost header and library. In my case simuPOP picked up a system boost header but tried to use conda boost libraries, and I suppose something similar happens on your side. I stopped bundling boost (#71) because of long time criticism and because  installing boost has become easier over the years (e.g. from conda), but problems can still arise in a complex environment with multiple versions of boost libraries.

Anyway, I have [reverted #71](https://github.com/BoPeng/simuPOP/commit/f814c9b4d90ebb1f347acd60f3ccef248099e0c8) and bundles boost 1.70 with the installer. Please checkout the latest master and try again, which should download boost 1.70.0 and use. Please remove existing boost (e.g. `boost` directory under conda include directory) since it could still cause trouble. I will try to create a conda release later today since conda-forge has only 1.0.8 version of simuPOP for linux.

**Comment by sasuke79** [comment]
It doesn't build now:

_configtest.cxx:3:6: error: ‘_S_word_bit’ in namespace ‘std’ does not name a type
 std::_S_word_bit;

...
In file included from src/utility.h:52:0,
                 from src/population.h:33,
                 from build/std/population.cpp:25:
src/pedigree.h:113:15: error: ‘it’ was not declared in this scope
   return toID(it->second->info(m_motherIdx));
               ^
src/simuPOP_cfg.h:109:42: note: in definition of macro ‘toID’
 #define toID(val)  (static_cast<size_t>((val) + 0.5))
                                          ^~~
In file included from build/std/population.cpp:26:0:
src/pedigree.h: In member function ‘simuPOP::Individual& simuPOP::Pedigree::indByID(size_t) const’:
src/pedigree.h:152:3: error: ‘IdMap’ has not been declared
   IdMap::iterator it = m_idMap.find(id);
   ^~~~~
src/pedigree.h:155:7: error: ‘it’ was not declared in this scope
   if (it == m_idMap.end())
       ^~
src/pedigree.h:155:13: error: ‘m_idMap’ was not declared in this scope
   if (it == m_idMap.end())
             ^~~~~~~
src/pedigree.h:157:11: error: ‘it’ was not declared in this scope
   return *it->second;
           ^~
error: command 'gcc' failed with exit status 1

**Comment by BoPeng** [comment]
I am trying to use `autoconf` like stuff to detect system configurations which might fail on your system now. Could you try

```
git checkout 243a950feaf8503ad485234e5123d5b16d283004
```
and see if the embedded boost work?

**Comment by BoPeng** [comment]
I have fixed all compiling related issues, especially support for the newer libc++ library on mac (#70), and simuPOP should be working all right on all major systems. The easiest way to install it now is to use conda and install it with

```
conda install -c conda-forge simuPOP
```
