### ISSUE TITLE
Maternal inheritance of trait problem

### ISSUE THREAD

**Issue by emmcarr** [BoPeng/simuPOP#79]
Hi,
I am simulating a population that shows maternally directed learning of foraging grounds, so that 'feeding_ground' and stable isotopes 'nitrogen' and 'carbon' are set as info fields. For the simulation set up, the stable isotope values are sampled from a distribution. i.e., line 48 of attached file:

```
def postop_processing(pop):
    for i in range(0, pop.numSubPop()):
        for individual in pop.individuals(i):
            # The feeding ground is fixed at birth (inherited from mother)
            # The C and N values are sampled from a distribution based on the feeding ground each year
            # The 'feeding_ground' info field is a float. We cannot use that as an array index so convert to an int
            feeding_ground = int(individual.info('feeding_ground'))
            individual.setInfo(numpy.random.normal(mean_C[feeding_ground], numpy.sqrt(variance_C[feeding_ground])), 'carbon')
            individual.setInfo(numpy.random.normal(mean_N[feeding_ground], numpy.sqrt(variance_N[feeding_ground])), 'nitrogen')
```
 

Then for subsequent generations the isotope values should be maternally inherited rather than sampled from a distribution. i.e., line 171 of attached file
```
            simuPOP.RandomMating(ops=[simuPOP.MitochondrialGenoTransmitter(),
                                      simuPOP.MendelianGenoTransmitter(),
                                      simuPOP.IdTagger(),
                                      simuPOP.InheritTagger(mode=simuPOP.MATERNAL, infoFields=['nitrogen', 'carbon', 'native_breeding_ground', 'feeding_ground']),
                                      simuPOP.PedigreeTagger()],
                                 subPops=[(sub_population, 7) for sub_population in range(0, sub_population_count)],
                                 weight=1)],
                subPopSize=configure_new_population_size
                                                ),
```
However, the nitrate and carbon values are not showing direct maternal inheritance, although they are from the same distribution that the mother's values come from.

I'm not really sure what to do here, so any suggestions would be welcome. Attached is the script plus input files. 

cheers
Emma

[whalesJuly19.txt](https://github.com/BoPeng/simuPOP/files/3389286/whalesJuly19.txt)
[mtDNA_1.txt](https://github.com/BoPeng/simuPOP/files/3389287/mtDNA_1.txt)
[SNP_1.txt](https://github.com/BoPeng/simuPOP/files/3389288/SNP_1.txt)

**Comment by BoPeng** [comment]
It is a long script and would take a while to debug. Did you try to [dump the population](http://simupop.sourceforge.net/manual_svn/build/refManual_ch3_sec14.html#Dumper) and check if the `feeding_ground` and mating scheme are correctly handled? I meant something like

```
preOps = [... simuPOP.Dumper(... output='!"before_mating_%d" % gen')]
postOps = [... simuPOP.Dumper(... output='!"before_mating_%d" % gen') ]
```
Then you can find an offspring, check its sex, `feeding_ground` etc, then find her parents from `before_mating...` and verify...

You could also use an [`Stat` operator](http://simupop.sourceforge.net/manual_svn/build/refManual_ch3_sec11.html#class-stat) (e.g. `Stat(meanOfInfo='feeding_ground', subPops='vsp defined for female in a feeding site')`) to check if the feeding_ground in any `feeding_site` has stayed constant.

**Comment by emmcarr** [comment]
Hi Bo,
Yes we have been going through the output that way (line 207):

 ped = simuPOP.Pedigree(pop);
    print("This is the pedigree stuff")
    simuPOP.dump(pop);

which produces:

Information fields:

age ind_id father_id mother_id nitrogen carbon feeding_ground
native_breeding_ground migrate_to

population size: 1955 (2 subpopulations with 976 (A), 979 (B) Individuals)
---> all the data follow!
e.g.,

SubPopulation 0 (A), 976 Individuals:

   0: FU
1111111111110111101001110101101110101011110011111011101111111111111111101111111110111110111111110110
18 |
1111011111111111101011110111101110111101110011110111101001111010111111101111111100111110111111110110
_ |  1 3725 2292 2489 5.04569 16.7788 0 0 0


We have confirmed that the feeding and breeding grounds are being assigned
as expected, as well as the mtDNA and SNP genotypes.

It's just that the exact values of nitrogen and carbon are not being passed
down to the offspring when expected.

cheers
Emma




Rutherford Discovery Fellow | Senior Research Fellow
Te Kura Mātauranga Koiora | School of Biological Sciences
Te Whare Wānanga o Tāmaki Makaurau | University of Auckland
e: e.carroll@auckland.ac.nz | p: +64 9 923 8239 | t: @EmzLCarroll
w: whalednalab.auckland.ac.nz |
https://unidirectory.auckland.ac.nz/people/e-carroll

**Comment by BoPeng** [comment]
It is hard to imagine that 

```
                                      simuPOP.InheritTagger(mode=simuPOP.MATERNAL, infoFields=['nitrogen', 'carbon', 'native_breeding_ground', 'feeding_ground']),

```
passed breeding ground info fields correctly but left `nitrogen` and `carbo` wrong.

**Comment by BoPeng** [comment]
>  for subsequent generations the isotope values should be maternally inherited rather than sampled from a distribution.

Are you saying that the sampling only happens once? This is not what your code does, because

```
        postOps = [

        # Determine the isotopic ratios in individuals
        simuPOP.PyOperator(func=postop_processing),
```
means that `postop_processing` will be called after mating at each generation.
