### ISSUE TITLE
Problem with LD Computation

### ISSUE THREAD

**Issue by EricFriedlander** [BoPeng/simuPOP#84]
Hi,

I keep getting the following error: "SystemError: stator.cpp: 2296 Calculated D' value -1 out of range of [-1, 1]"
I'm not exactly sure why its throwing an error since -1 is in [-1,1]. The code I'm using to generate this error is:

```out= []
    for k in range(reps):
        print(k)
        pop1 = pop.clone()
        pop1 = pop.clone()
        initial_A = int(n*init)
        means = np.random.beta(4*n*m, 4*n*m, size=num_loci)
        genotype_focal=  [np.random.binomial(1, p) for p in means]
        ld_sets = [(selLocus, i, 1, 1) for i in loci[1:]]
        for i, ind in enumerate(pop1.individuals()):
                if i < initial_A:
                    genotype = tuple([1] + genotype_focal)
                    ind.setGenotype(genotype, ploidy=0)
                    genotype = tuple([1] + genotype_focal)
                    ind.setGenotype(genotype, ploidy=1)
                else:
                    genotype_non_focal = [np.random.binomial(1, p) for p in means]
                    genotype = tuple([0] + genotype_non_focal)
                    ind.setGenotype(genotype, ploidy=0)
                    genotype_non_focal = [np.random.binomial(1, p) for p in means]
                    genotype = tuple([0] + genotype_non_focal)
                    ind.setGenotype(genotype, ploidy=1)
        pop1.dvars().freqA = []
        pop1.dvars().ld = []
        g = pop1.evolve(initOps=[sim.Stat(alleleFreq=loci, LD=ld_sets),
                                        sim.PyExec('ld.append([LD[%d][i] for i in %s])' % (selLocus, loci[1:])),
                                        sim.PyExec('freqA.append(alleleFreq)')],
                            preOps=[
                                sim.MapSelector(loci=selLocus, fitness={(0, 0): 1, (0, 1): 1+s, (1, 1): 1+2*s}),
                                        sim.SNPMutator(u=m, v=m)
                                    ],
                            matingScheme=sim.RandomMating(ops=sim.Recombinator(rates=rec_rates, loci=loci), subPopSize=model),
                            postOps=[sim.Stat(alleleFreq=loci, LD=ld_sets),
                                        sim.PyExec('ld.append([LD[%d][i] for i in %s])' % (selLocus, loci[1:])),
                                        sim.PyExec('freqA.append(alleleFreq)')],
                            gen = gens_sim)
        out.append([pop1.dvars().freqA, pop1.dvars().ld])
```

Any idea what's going wrong?

**Comment by BoPeng** [comment]
https://github.com/BoPeng/simuPOP/blob/5e9b389c523ca03695a60e52cb255d2724ffda30/src/stator.cpp#L2295-L2296

is the code where the error happens, which looks ok and seems to be even tolerable to floating point errors. Let me see if I can reproduce your error.

**Comment by BoPeng** [comment]
I cannot run your example. Could you please provide a minimal test case? The easiest thing to do might be adding

```
PyOperator(lambda pop: pop.save('test.pop')
```
before the operator that causes the exception, and then from the command line do

```
pop.= loadPopulation('test.pop')
stat(pop, LD=...)
```
and see if you can trigger this error.

If so, please send me `test.pop` and the options you use for LD calculation.

Thanks,

**Comment by EricFriedlander** [comment]
Hi Bo. Unfortunately I am not able to create a reproducible version of the error. That best I could do was add 
`PyOperator(lambda pop: pop.save('test.pop'))`
so that its executed before Stat and the population saves before the error. However, when I load the saved population and run stat on it, it does not throw an error (however the LD_prime values do appear to be slightly below -1).
I've attached the population file (converted to text file, I hope that still works) if you find it helpful. I will note that it seems to only throw the error sometimes (and on different repetitions), despite the fact that I've set the seed. Perhaps this points to a floating point error?

I'm trying to run:
```
Stat(alleleFreq=loci, LD=ld_sets),
PyExec('ld.append([LD[%d][i] for i in %s])' % (selLocus, loci[1:])),
PyExec('freqA.append(alleleFreq)')
```
with 
```
loci = [0,1,2,3,4,5]
ld_sets = [(0, i, 1, 1) for i in loci[1:]]
``` 
[test.txt](https://github.com/BoPeng/simuPOP/files/5151955/test.txt)

**Comment by BoPeng** [comment]
Let me see why the result is slightly below -1. In the mean time, `DBG_ASSERT` is not triggered in optimized mode so you can bypass this problem for now by setting
```
setOptions(optimied=True)
```
before running the simulation.

**Comment by BoPeng** [comment]
Ok, the problem is that `Dp =D/D_max` and when `D_max` is small, and `D ~ D_max`, the difference is magnified and making `Dp < -1` more than the tolerance of the algorithm.

I have submitted a patch to stop checking this and force `Dp` to be between -1 and 1. If it is difficult for you to compile simuPOP from source (quite involved since there are a bunch of dependencies), you can set `optimized=True` to bypass the sanity check.

**Comment by BoPeng** [comment]
PS: If you use conda, you can

```
conda install simuPOP -c conda-forge
```
to install all the dependencies, then
```
git clone https://github.com/BoPeng/simuPOP
cd simuPOP
python setup.py install
```
to compile simuPOP from source.

**Comment by EricFriedlander** [comment]
Thanks so much!
