### ISSUE TITLE
got multiple values for argument 'numOffspring'

### ISSUE THREAD

**Issue by nclowell** [BoPeng/simuPOP#85]
Hi Bo,

I'm getting the error ``TypeError: __init__() got multiple values for argument 'numOffspring'`` in the following block of code:

```
pop.evolve(preOps=[sim.PySelector(func=get_fitness_hybrid)],
           matingScheme=sim.HeteroMating([sim.CloneMating(weight=-1),
                                          sim.RandomMating(sim.PyParentsChooser(gameteEscapeChooser),
                                                           sim.OffspringGenerator(ops=[sim.MendelianGenoTransmitter(), 
                                                                                       sim.ParentsTagger(), 
                                                                                       sim.IdTagger()]),
                                                            subPops=hybrid_index, 
                                                            numOffspring=2)],
                                           subPopSize=scaleGameteEscape(pop)), gen = 1)
```
I'm not sure what other value is being read by ``numOffspring`` other than the value I provided. I've tried removing most arguments within this ``pop.evolve()`` function to see if they are causing the error indirectly, but I consistently get the same error so long as I provide any value to ``numOffspring``. 

Do you have any insights?

Thanks!

Natalie

**Comment by BoPeng** [comment]
This looks very strange. What is your os, version of python and simupop?

**Comment by nclowell** [comment]
I thought so too!

Ubuntu 19.04
python 3.7.3
simuPOP 1.1.10.9

**Comment by BoPeng** [comment]
Did you install from conda-forge?

**Comment by nclowell** [comment]
Yes, although it was a couple of years ago.

**Comment by BoPeng** [comment]
The error message was confusing but if you look at

```
sim.RandomMating(sim.PyParentsChooser(gameteEscapeChooser),
                                                           sim.OffspringGenerator(ops=[sim.MendelianGenoTransmitter(), 
                                                                                       sim.ParentsTagger(), 
                                                                                       sim.IdTagger()]),
                                                            subPops=hybrid_index, 
                                                            numOffspring=2)],
```

and the interface definition at https://github.com/BoPeng/simuPOP/blob/master/src/__init__.py#L750 , you are passing too many parameters.

I think you are trying to use `sim.HomoMating`.

**Comment by nclowell** [comment]
Interesting! I'm simulating age structure (with the work around provided through clone mating suggested at http://simupop.sourceforge.net/manual_svn/build/userGuide_ch6_sec4.html). I was under the impression when simulating age structure with simuPOP I would always need a HeteroMating scheme, because I would need the CloneMating to retain individuals into the next generation and an additional mating scheme (RandomMating) to produce new offspring. Is this incorrect?

**Comment by BoPeng** [comment]
No. I was saying that instead of using

```
HeteroMating([RandomMating...]
```
you should do
```
HeteroMating([HomoMating...])
```
because `RandoMating` is a special case of `HomoMating` and you will have to use `HomoMating` when you pass your own offspring generator. Check the definition of `RandomMating` to see what I meant.

**Comment by nclowell** [comment]
Thank you for the clarification!
