### ISSUE TITLE
demographic Ne with age structure?

### ISSUE THREAD

**Issue by nclowell** [BoPeng/simuPOP#86]
Hi Bo,

I'm using a ``HeteroMating`` scheme (``CloneMating`` and ``RandomMating``) to include age structure in my model. I had been using the built-in demographic Ne estimator previously when I used discrete generations, and realized that it was still estimating Ne now that I have overlapping generations without warning/error despite the violated assumption of discrete generations. The Ne results seemed quite high, and indeed were higher than when I manually estimate Ne using the same equation as in simuPOP. 

I'm wondering if you could shed some light on what the built-in demographic Ne estimator is doing under the hood when there is a ``CloneMating`` scheme (e.g., is N the census size of the subpop or just the number of potential parents of the random mating scheme, etc.), and if you know of anyone who has found an effective way to estimate demographic Ne with age structure in simuPOP.

Thank you!

Natalie

**Comment by BoPeng** [comment]
The `Stat(Ne)` operator does not know anything about age structured population and will just use all individuals for the Ne calculation by default. You could limit calculation to certain age (define vsp and use parameter `subPops` for `Stat`). Then when you evolve your population the age group will not (at least less) overlapping for the calculation of `Ne`.

**Comment by nclowell** [comment]
Good idea - thank you!
