### ISSUE TITLE
ImportPopulation() and linkage between loci

### ISSUE THREAD

**Issue by ChrystelleDelord** [BoPeng/simuPOP#88]
Dear simuPOP users,

Before I go too deep in my issue here, I just wanted to check something that actually might be quite simple:

I need to import a population at equilibrium (with ~2000 diploid individuals and ~1000 biallelic loci), in genepop format generated from a coalescent simulator, in order to initialize a forward-in-time simulation in simuPOP. 

I was just wondering; in the case where importPopulation() was used, how do loci behave during the pop.evolve() phase? 
If I just use a basic RandomMating() scheme, do loci act like they were independent, or should I specify recombination rates within the RandomMating()?

Indeed, in my case, I also had to expand the initial, imported population to increase the number of simulated individuals (using the function pop.resize() with argument _Propagate=True_) but I was surprised that, no matter how many generations I simulate afterwards as a burn-in, linkage disequilibrium stays quite high and the LD-based effective size Ne is much smaller than the actual number of individuals (which I think should not be the case if I had simulated my "Wright-Fisher" population correctly). 

Thank you very much, I wish you all very nice day,

Chrystelle

**Comment by BoPeng** [comment]
Did you use a single chromosome with all loci, or many chromosomes each with one locus? It sounds like a silly question but if you import all loci in a single chromosome, they segregate with each other as haplotypes, unless you intentionally introduce a recombinator to specify recommbination rates between adjacent loci. If you create many chromosomes each with a single locus, they will "free recombine" so no LD will exist.

**Comment by ChrystelleDelord** [comment]
Dear Bo,

Thank you for your feedback, I am sorry I had to write my message quite quickly yesterday and was not able to provide my code.

In my initial genepop file 'fastSimcoal_output.gen', all loci are independent, biallelic SNP. Then, I used the following code to load that population into simuPOP:

```
from simuOpt import setOptions
setOptions(alleleType='binary', numThreads=0) 

import simuPOP as sim
from simuPOP.utils import importPopulation
pop = importPopulation(format='genepop', filename='fastSimcoal_output.gen', adjust=-1)
print('Retrieving initial population of ', pop.numSubPop(), ' subpopulations with ', pop.subPopSizes(), ' individuals and ', pop.numLoci()[0], ' locis in the Genepop input file.', '\n', sep='')
sim.dump(pop, loci=range(10), max=5, structure=False)
```

```
Retrieving initial population of 2 subpopulations with (10000, 10000) individuals and 1000 locis in the Genepop input file.

SubPopulation 0 (), 10000 Individuals:
   0: MU 1010000101 | 0001110011 
   1: MU 1000101111 | 1000000100 
   2: MU 0101110110 | 0010011001 
   3: MU 1110101111 | 1001001110 
   4: MU 1001011100 | 0010110011 
SubPopulation 1 (), 10000 Individuals:
10000: MU 0000111011 | 0110000100 
```
I could see my population was correctly imported. Then, I resize and evolve this population as follows (pop sizes are constant at first, decrease between gen 400 to 403, and then are stable again):

```
pop.resize([20000, 20000], propagate=True)

M = [[0.00, 0.20],
         [0.20, 0.00]]
    
pop.setInfoFields(['ind_id','migrate_to'])
        
pop.evolve(
     initOps=[sim.InitSex(maleProp=0.5)], 
     preOps = [
           sim.Migrator(rate=M, mode=sim.BY_PROPORTION),
           sim.SNPMutator(u=0.00000001),
           sim.ResizeSubPops(subPops=[0,1], proportions=(0.827, 0.827), begin=400, end=403)
            ],
            # Simulation of a ~WF population with random-mating. For now, the RandomMating() scheme is set with default arguments.         
     matingScheme = sim.RandomMating(),
     postOps = [
                sim.Stat(popSize=True, structure=range(pop.numLoci()[0]), LD=[0,1], step=2),
                sim.Stat(effectiveSize=range(100), subPops=[0,1], vars='Ne_LD', step=10),
                sim.PyEval(r"'Gen %d:\t%s\t%.6f\t%.6f\n' % (gen, subPopSize, F_st, LD[0][1])", step=2),
                sim.PyEval(r"'LDNe (gen %d): %.1f (%.1f - %.1f)\n' % tuple([gen] + Ne_LD[0.05])", step=10)
           ],
                gen=501
)
```
Here are a few output lines from the previous code: 

```
Gen:    No Individuals: Fst:            LD[0][1]:
Gen 0:	[20000, 20000]	0.000041	0.004080
LDNe (gen 0): 1152.4 (1103.9 - 1202.3)
Gen 2:	[20000, 20000]	0.000040	0.004309
Gen 4:	[20000, 20000]	0.000038	0.005115
Gen 6:	[20000, 20000]	0.000043	0.006514
Gen 8:	[20000, 20000]	0.000038	0.004525
Gen 10:	[20000, 20000]	0.000045	0.005564
LDNe (gen 10): 782.6 (750.2 - 815.8)
Gen 12:	[20000, 20000]	0.000042	0.005925
Gen 14:	[20000, 20000]	0.000036	0.006467
Gen 16:	[20000, 20000]	0.000033	0.005417
Gen 18:	[20000, 20000]	0.000041	0.003600
Gen 20:	[20000, 20000]	0.000041	0.002906
LDNe (gen 20): 614.6 (589.7 - 640.0)
[...]
LDNe (gen 390): 63.8 (61.2 - 66.4)
Gen 392:	[20000, 20000]	0.000038	0.011792
Gen 394:	[20000, 20000]	0.000033	0.010640
Gen 396:	[20000, 20000]	0.000041	0.011019
Gen 398:	[20000, 20000]	0.000042	0.010393
Gen 400:	[16534, 16534]	0.000041	0.011151
LDNe (gen 400): 62.4 (59.9 - 65.0)
Gen 402:	[11299, 11299]	0.000100	0.009873
Gen 404:	[9341, 9341]	0.000091	0.005939
Gen 406:	[9341, 9341]	0.000074	0.006900
Gen 408:	[9341, 9341]	0.000108	0.009235
Gen 410:	[9341, 9341]	0.000114	0.012612
LDNe (gen 410): 58.2 (55.9 - 60.6)
[...]
LDNe (gen 490): 39.2 (37.6 - 40.8)
Gen 492:	[9341, 9341]	0.000093	0.021597
Gen 494:	[9341, 9341]	0.000130	0.023688
Gen 496:	[9341, 9341]	0.000087	0.023990
Gen 498:	[9341, 9341]	0.000072	0.023572
Gen 500:	[9341, 9341]	0.000069	0.026631
LDNe (gen 500): 39.1 (37.5 - 40.7)
(end)
```
I was expecting a LD decay over time which is not really the case, and I am also surprised to obtain such small effective size LDNe values.

I also tried to run the previous code without resizing the population, in order to avoid genotype duplicates, and realized that LDNe (as currently calculated, i.e for the whole population and using 100 loci) is still much smaller than N, and keeps decreasing over time. It was also the case when running a code with a single population instead of two sub-populations with high, symmetric migration rates. 
So maybe this has actually nothing (or, not everything) to do with importPopulation() nor pop.resize(Propagate=True)? 
Maybe I should just use another mating scheme to ensure that almost all individuals produce an offpsring?

Apart from this, am I still missing something about how to import loci with the function importPopulation() to ensure they are freely recombining?

Thank you so much for your help,
Best wishes,

Chrys

**Comment by BoPeng** [comment]
You imported all loci as a single chromosome so they are co-segregating. If you want to simulate free recombining,  you can add a Recombination with rates=0.5.

**Comment by ChrystelleDelord** [comment]
Many thanks, Bo, it is indeed much more logical this way!
