### ISSUE TITLE
Clonal evolution

### ISSUE THREAD

**Issue by cruzan-lab** [BoPeng/simuPOP#90]
I'm unable to implement selection (fitness) using `RandomSelection`:

```
    matingScheme=sim.RandomSelection(ops=[
        sim.ParentsTagger(infoFields='parent_idx'),
        sim.MapSelector(loci=0, fitness={(0,0):1, (0,1):0, (1,1):0}),
        sim.CloneGenoTransmitter(),
        ]),
```
I have tried `MapSelector` in `preops` as well and numerous other ways to implement fitness.

**Comment by BoPeng** [comment]
`MapSelector` removes offspring based on genotype, which are all zero before `CloneGeneTransmitter` assigns any. You can try to put `ClineGenoTransmitter()` before `MapSelector` and see.

**Comment by cruzan-lab** [comment]
I moved the MapSelector as you suggested. It gives me a fitness of 0.0 for ind0 and ind1 regardless of the genotype.

**Comment by cruzan-lab** [comment]
Based on your description, perhaps I am approaching this wrong. Perhaps that is why the locus[0] and locus[1] appear to be inherited independently of each other. I want to simulate single cell lineages undergoing mitosis to reproduce. I thought the CloneGenoTransmitter would do that based on the documentation (I copied commands from the asexual reproduction example). Can you suggest a better approach?

**Comment by BoPeng** [comment]
> Perhaps that is why the locus[0] and locus[1] appear to be inherited independently of each other

They are segregated together. Not sure what exactly you tried to do but your mutation happens to both loci and selection acts on the first locus only. Since you remove all offspring with mutation on locus 0, it is natural to have allele frequency 0 at locus 0 all the time, and 0.5 or 1 at locus 1.

**Comment by cruzan-lab** [comment]
Yes, I get that. I' was worried it was not working that way because print(ind.fitness) always returns 0.0 regardless of the fitness at the two loci.

**Comment by BoPeng** [comment]
At least the selector works as expected according to allele frequencies of the offspring population.
